"""Tests for core.make_targets.is_autogenerated_header — deciding whether a
generated header is produced by the project's OWN build (jsonproc /
AUTO_GEN_TARGETS), so PorySuite never hand-writes a build artifact.
"""
import os
import sys
import tempfile
import unittest

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
for _p in (ROOT_DIR, os.path.join(ROOT_DIR, "core")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from core.make_targets import is_autogenerated_header


class MakeTargetsTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = self.tmp.name

    def tearDown(self):
        self.tmp.cleanup()

    def _write(self, name, text):
        with open(os.path.join(self.root, name), "w", encoding="utf-8") as f:
            f.write(text)

    def test_jsonproc_rule_detected(self):
        # The exact shape of pokefirered's json_data_rules.mk.
        self._write("json_data_rules.mk",
            "AUTO_GEN_TARGETS += $(DATA_SRC_SUBDIR)/items.h\n"
            "$(DATA_SRC_SUBDIR)/items.h: $(DATA_SRC_SUBDIR)/items.json $(DATA_SRC_SUBDIR)/items.json.txt\n"
            "\t$(JSONPROC) $^ $@\n")
        self.assertTrue(is_autogenerated_header(self.root, "items.h"))

    def test_autogen_targets_line_alone_detected(self):
        self._write("foo.mk", "AUTO_GEN_TARGETS += $(DATA_SRC_SUBDIR)/items.h\n")
        self.assertTrue(is_autogenerated_header(self.root, "items.h"))

    def test_other_header_not_falsely_matched(self):
        # A project that auto-gens wild_encounters.h but NOT items.h.
        self._write("json_data_rules.mk",
            "AUTO_GEN_TARGETS += $(DATA_SRC_SUBDIR)/wild_encounters.h\n"
            "$(DATA_SRC_SUBDIR)/wild_encounters.h: $(DATA_SRC_SUBDIR)/wild_encounters.json\n")
        self.assertFalse(is_autogenerated_header(self.root, "items.h"))
        self.assertTrue(is_autogenerated_header(self.root, "wild_encounters.h"))

    def test_no_makefiles_returns_false(self):
        self.assertFalse(is_autogenerated_header(self.root, "items.h"))

    def test_empty_args_return_false(self):
        self.assertFalse(is_autogenerated_header("", "items.h"))
        self.assertFalse(is_autogenerated_header(self.root, ""))

    def test_rule_in_plain_makefile(self):
        self._write("Makefile",
            "src/data/items.h: src/data/items.json\n\tjsonproc $< $@\n")
        self.assertTrue(is_autogenerated_header(self.root, "items.h"))


if __name__ == "__main__":
    unittest.main()
