"""Dynamic Overworld Palettes (DOWP) patch for pokefirered decomp.

Applies the community-standard dynamic palette system that allows each
overworld sprite to have its own unique palette instead of being locked
to the 4 shared NPC palette slots (Blue, Pink, Green, White).

After this patch:
  - Each sprite loads its palette on demand when it spawns
  - Palettes are freed when no sprites use them anymore
  - Reflection palettes are generated by tinting the base palette at runtime
  - Up to 16 unique overworld palettes can be on screen simultaneously
  - Users can add new sprites with fully custom palettes

This is a ONE-WAY patch. It modifies multiple C source files in the project.

Based on the community implementations by Navenatox, ExpoSeed, and others.
Adapted for pokefirered decomp by PorySuite-Z.
"""

from __future__ import annotations

import os
import re
from typing import List, Tuple

MARKER_FILE = ".porysuite_dowp_enabled"


def is_dowp_enabled(project_root: str) -> bool:
    """Check whether the dynamic OW palette patch has actually been applied.

    Verifies by inspecting the real source code for DOWP signatures,
    not just checking for the marker file.  This handles cases where
    the pokefirered folder was replaced or restored from a clean copy.
    If the source is patched but the marker is missing, re-creates it.
    If the marker exists but the source is unpatched, removes the stale marker.
    """
    marker_path = os.path.join(project_root, MARKER_FILE)
    marker_exists = os.path.isfile(marker_path)

    # Check the actual source for DOWP signatures
    eom_path = os.path.join(project_root, "src", "event_object_movement.c")
    source_patched = False
    if os.path.isfile(eom_path):
        try:
            with open(eom_path, encoding="utf-8", errors="replace") as f:
                eom_text = f.read()
            # These are unique strings that only exist after DOWP patching
            source_patched = (
                "FieldEffectFreePaletteIfUnused(paletteNum);" in eom_text
                and "// DOWP: palettes load on demand" in eom_text
            )
        except OSError:
            # Can't read the file — fall back to marker
            return marker_exists

    # Sync the marker file with reality
    if source_patched and not marker_exists:
        # Source is patched but marker is missing — recreate it
        try:
            with open(marker_path, "w") as f:
                f.write(
                    "Dynamic Overworld Palettes (DOWP) enabled by PorySuite-Z.\n"
                    "This file marks that the DOWP patch has been applied to this project.\n"
                    "Do not delete — PorySuite-Z uses this to detect patch status.\n"
                )
        except OSError:
            pass
    elif not source_patched and marker_exists:
        # Marker is stale (project folder was replaced) — remove it
        try:
            os.remove(marker_path)
        except OSError:
            pass

    return source_patched


def _read(path: str) -> str:
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def _write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def _replace_once(text: str, old: str, new: str, desc: str) -> Tuple[str, bool]:
    """Replace exactly one occurrence of 'old' with 'new'. Returns (new_text, success)."""
    count = text.count(old)
    if count == 0:
        return text, False
    if count > 1:
        # Try to still apply — replace first occurrence
        idx = text.index(old)
        text = text[:idx] + new + text[idx + len(old):]
        return text, True
    return text.replace(old, new), True


def _replace_all(text: str, old: str, new: str) -> str:
    """Replace all occurrences."""
    return text.replace(old, new)


def scan_dowp_risks(project_root: str) -> List[str]:
    """Scan the project for known DOWP compatibility issues.
    Returns a list of plain-English warning strings (empty list = no known risks).
    """
    warnings: List[str] = []

    gfx_candidates = [
        os.path.join(project_root, "src", "data", "object_events", "object_event_graphics_info.h"),
        os.path.join(project_root, "src", "data", "graphics", "object_events", "graphics_info.h"),
    ]
    none_tag_structs: List[str] = []
    all_tags: set = set()

    for gfx_path in gfx_candidates:
        if not os.path.isfile(gfx_path):
            continue
        try:
            with open(gfx_path, encoding="utf-8", errors="replace") as f:
                text = f.read()
            for m in re.finditer(
                r'const struct ObjectEventGraphicsInfo\s+(\w+)\s*=\s*\{([^}]*)\}',
                text, re.DOTALL
            ):
                struct_name = m.group(1)
                body = m.group(2)
                tag_m = re.search(r'\.paletteTag\s*=\s*(\w+)', body)
                if tag_m:
                    tag = tag_m.group(1)
                    if tag == "OBJ_EVENT_PAL_TAG_NONE":
                        none_tag_structs.append(struct_name)
                    else:
                        all_tags.add(tag)
        except Exception:
            pass

    if none_tag_structs:
        count = len(none_tag_structs)
        names = ", ".join(none_tag_structs[:4])
        if count > 4:
            names += f" (+{count - 4} more)"
        warnings.append(
            f"{count} sprite definition(s) use OBJ_EVENT_PAL_TAG_NONE as their palette tag. "
            f"Under DOWP these sprites won't load a palette and will display the wrong colours.\n"
            f"Affected: {names}\n"
            f"Fix: assign each a unique OBJ_EVENT_PAL_TAG_* constant in object_event_graphics_info.h."
        )

    if len(all_tags) > 12:
        warnings.append(
            f"Your project uses {len(all_tags)} unique sprite palette tags. "
            f"The GBA only supports 16 OBJ palette slots at once. "
            f"The player sprite and its reflection use ~2–3 slots, and any custom HUD "
            f"overlay takes another. If more unique NPC sprites appear on screen "
            f"simultaneously than available slots, extra sprites will display wrong colours."
        )

    return warnings


def remove_dowp_patch(project_root: str) -> Tuple[bool, List[str], List[str]]:
    """Reverse the Dynamic Overworld Palettes patch.

    Restores each modified source file to its pre-DOWP state by applying each
    patch in reverse.  Returns (success, reverted_descriptions, failed_descriptions).
    """
    reverted: List[str] = []
    failed: List[str] = []

    # ── field_effect_helpers.c ────────────────────────────────────────────────
    feh_c_path = os.path.join(project_root, "src", "field_effect_helpers.c")
    if os.path.isfile(feh_c_path):
        fehc = _read(feh_c_path)

        old_refl_map = (
            "    reflectionSprite->oam.paletteNum = "
            "gReflectionEffectPaletteMap[reflectionSprite->oam.paletteNum];"
        )
        tint_block = re.compile(
            r"    // DOWP: generate tinted reflection palette dynamically\n"
            r"    \{.*?\n    \}",
            re.DOTALL,
        )
        if tint_block.search(fehc):
            fehc = tint_block.sub(old_refl_map, fehc, count=1)
            reverted.append("SetUpReflection: reflection map lookup restored")
        elif old_refl_map in fehc:
            reverted.append("SetUpReflection: already restored")
        else:
            failed.append("Could not restore SetUpReflection")

        old_regular_refl = (
            "static void LoadObjectRegularReflectionPalette(struct ObjectEvent * objectEvent, u8 paletteIndex)\n"
            "{\n"
            "    const struct ObjectEventGraphicsInfo * graphicsInfo;\n"
            "\n"
            "    graphicsInfo = GetObjectEventGraphicsInfo(objectEvent->graphicsId);\n"
            "    if (graphicsInfo->reflectionPaletteTag != OBJ_EVENT_PAL_TAG_NONE)\n"
            "    {\n"
            "        if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
            "            LoadPlayerObjectReflectionPalette(graphicsInfo->paletteTag, paletteIndex);\n"
            "        else if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
            "            LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, paletteIndex);\n"
            "        else\n"
            "            PatchObjectPalette(GetObjectPaletteTag(paletteIndex), paletteIndex);\n"
            "        UpdateSpritePaletteWithWeather(paletteIndex);\n"
            "    }\n"
            "}"
        )
        new_regular_refl = (
            "static void LoadObjectRegularReflectionPalette(struct ObjectEvent * objectEvent, u8 paletteIndex)\n"
            "{\n"
            "    // DOWP: reflection palettes are now generated dynamically in SetUpReflection.\n"
            "    // This function just ensures weather tinting is applied.\n"
            "    const struct ObjectEventGraphicsInfo * graphicsInfo;\n"
            "\n"
            "    graphicsInfo = GetObjectEventGraphicsInfo(objectEvent->graphicsId);\n"
            "    if (graphicsInfo->reflectionPaletteTag != OBJ_EVENT_PAL_TAG_NONE)\n"
            "    {\n"
            "        UpdateSpritePaletteWithWeather(paletteIndex);\n"
            "    }\n"
            "}"
        )
        fehc, ok = _replace_once(fehc, new_regular_refl, old_regular_refl, "")
        if ok:
            reverted.append("LoadObjectRegularReflectionPalette: restored")
        elif old_regular_refl in fehc:
            reverted.append("LoadObjectRegularReflectionPalette: already restored")
        else:
            failed.append("Could not restore LoadObjectRegularReflectionPalette")

        _write(feh_c_path, fehc)
    else:
        failed.append("field_effect_helpers.c not found")

    # ── event_object_movement.h ───────────────────────────────────────────────
    eomh_path = os.path.join(project_root, "include", "event_object_movement.h")
    if os.path.isfile(eomh_path):
        eomh = _read(eomh_path)
        decl = "// DOWP: dynamic palette loading\nvoid LoadObjectEventPalette(u16 paletteTag);\n"
        if decl in eomh:
            eomh = eomh.replace("\n\n" + decl, "").replace(decl, "")
            _write(eomh_path, eomh)
            reverted.append("event_object_movement.h: LoadObjectEventPalette decl removed")
        elif "void LoadObjectEventPalette" not in eomh:
            reverted.append("event_object_movement.h: already clean")
        else:
            failed.append("event_object_movement.h: declaration in unexpected form — remove manually")
    else:
        failed.append("event_object_movement.h not found")

    # ── field_effect.h ────────────────────────────────────────────────────────
    feh_path = os.path.join(project_root, "include", "field_effect.h")
    if os.path.isfile(feh_path):
        feh = _read(feh_path)
        decl = "// DOWP: exported for dynamic palette freeing\nvoid FieldEffectFreePaletteIfUnused(u8 paletteNum);\n"
        if decl in feh:
            feh = feh.replace("\n\n" + decl, "").replace(decl, "")
            _write(feh_path, feh)
            reverted.append("field_effect.h: FieldEffectFreePaletteIfUnused decl removed")
        elif "FieldEffectFreePaletteIfUnused" not in feh:
            reverted.append("field_effect.h: already clean")
        else:
            failed.append("field_effect.h: declaration in unexpected form — remove manually")
    else:
        failed.append("field_effect.h not found")

    # ── field_effect.c ────────────────────────────────────────────────────────
    fe_path = os.path.join(project_root, "src", "field_effect.c")
    if os.path.isfile(fe_path):
        fe = _read(fe_path)
        fe, ok = _replace_once(fe,
            "void FieldEffectFreePaletteIfUnused(u8 paletteNum);",
            "static void FieldEffectFreePaletteIfUnused(u8 paletteNum);", "")
        if ok:
            reverted.append("FieldEffectFreePaletteIfUnused: decl restored to static")
        elif "static void FieldEffectFreePaletteIfUnused(u8 paletteNum);" in fe:
            reverted.append("FieldEffectFreePaletteIfUnused: decl already static")
        else:
            failed.append("Could not restore FieldEffectFreePaletteIfUnused decl")

        fe, ok = _replace_once(fe,
            "void FieldEffectFreePaletteIfUnused(u8 paletteNum)\n{",
            "static void FieldEffectFreePaletteIfUnused(u8 paletteNum)\n{", "")
        if ok:
            reverted.append("FieldEffectFreePaletteIfUnused: def restored to static")
        elif "static void FieldEffectFreePaletteIfUnused(u8 paletteNum)\n{" in fe:
            reverted.append("FieldEffectFreePaletteIfUnused: def already static")
        else:
            failed.append("Could not restore FieldEffectFreePaletteIfUnused def")
        _write(fe_path, fe)
    else:
        failed.append("field_effect.c not found")

    # ── event_object_movement.c ───────────────────────────────────────────────
    eom_path = os.path.join(project_root, "src", "event_object_movement.c")
    if not os.path.isfile(eom_path):
        return False, reverted, failed + ["event_object_movement.c not found"]

    eom = _read(eom_path)

    # Site 5 paletteNum
    eom, ok = _replace_once(eom,
        "    sprite->subspriteTables = graphicsInfo->subspriteTables;\n"
        "    sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
        "    if (!sprite->usingSheet)",
        "    sprite->subspriteTables = graphicsInfo->subspriteTables;\n"
        "    sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
        "    if (!sprite->usingSheet)", "")
    if ok:
        reverted.append("ObjectEventSetGraphicsId paletteNum: restored")
    else:
        if "sprite->oam.paletteNum = graphicsInfo->paletteSlot;" in eom:
            reverted.append("ObjectEventSetGraphicsId paletteNum: already restored")
        else:
            failed.append("Could not restore ObjectEventSetGraphicsId paletteNum")

    # Site 5 palette swap block
    eom, ok = _replace_once(eom,
        "    // DOWP: free old palette, load new one dynamically\n"
        "    {\n"
        "        u8 oldPalNum = sprite->oam.paletteNum;\n"
        "        LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
        "        FieldEffectFreePaletteIfUnused(oldPalNum);\n"
        "    }\n"
        "    \n"
        "    var = sprite->images->size / TILE_SIZE_4BPP;",
        "    if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
        "        PatchObjectPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "\n"
        "    if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
        "        LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "    \n"
        "    var = sprite->images->size / TILE_SIZE_4BPP;", "")
    if ok:
        reverted.append("ObjectEventSetGraphicsId: restored")
    else:
        failed.append("Could not restore ObjectEventSetGraphicsId")

    # Site 4 paletteNum
    eom, ok = _replace_once(eom,
        "        sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
        "        sprite->coordOffsetEnabled = TRUE;\n"
        "        sprite->data[0] = objectEventId;\n"
        "        objectEvent->spriteId = spriteId;\n"
        "        // DEBUG — log return-to-field spawn",
        "        sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
        "        sprite->coordOffsetEnabled = TRUE;\n"
        "        sprite->data[0] = objectEventId;\n"
        "        objectEvent->spriteId = spriteId;\n"
        "        // DEBUG — log return-to-field spawn", "")
    if ok:
        reverted.append("SpawnObjectEventOnReturnToField paletteNum: restored")
    else:
        failed.append("Could not restore SpawnObjectEventOnReturnToField paletteNum")

    # Site 4 reflection block
    eom, ok = _replace_once(eom,
        "    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;\n"
        "    // DOWP: load palette on demand\n"
        "    LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
        "\n"
        "    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;",
        "    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;\n"
        "    if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
        "        LoadPlayerObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "\n"
        "    if (graphicsInfo->paletteSlot >= PALSLOT_NPC_SPECIAL)\n"
        "        LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "\n"
        "    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;", "")
    if ok:
        reverted.append("SpawnObjectEventOnReturnToField reflection: restored")
    else:
        failed.append("Could not restore SpawnObjectEventOnReturnToField reflection")

    # Site 3
    eom, ok = _replace_once(eom,
        "        LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
        "        sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
        "        sprite->data[0] = localId;",
        "        sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
        "        sprite->data[0] = localId;\n"
        "        if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
        "            LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);", "")
    if ok:
        reverted.append("CreateFameCheckerObject: restored")
    else:
        failed.append("Could not restore CreateFameCheckerObject")

    # Site 2
    eom, ok = _replace_once(eom,
        "        LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
        "        sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
        "        sprite->coordOffsetEnabled = TRUE;\n"
        "        sprite->sVirtualObjId = virtualObjId;\n"
        "        sprite->sVirtualObjElev = elevation;",
        "        sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
        "        sprite->coordOffsetEnabled = TRUE;\n"
        "        sprite->sVirtualObjId = virtualObjId;\n"
        "        sprite->sVirtualObjElev = elevation;\n"
        "        if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
        "            LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);", "")
    if ok:
        reverted.append("CreateVirtualObject: restored")
    else:
        failed.append("Could not restore CreateVirtualObject")

    # Site 1
    eom, ok = _replace_once(eom,
        "    sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
        "    sprite->coordOffsetEnabled = TRUE;\n"
        "    sprite->data[0] = objectEventId;\n"
        "    objectEvent->spriteId = spriteId;\n"
        "    // DEBUG — log object spawn position",
        "    sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
        "    sprite->coordOffsetEnabled = TRUE;\n"
        "    sprite->data[0] = objectEventId;\n"
        "    objectEvent->spriteId = spriteId;\n"
        "    // DEBUG — log object spawn position", "")
    if ok:
        reverted.append("TrySetupObjectEventSprite paletteNum: restored")
    else:
        failed.append("Could not restore TrySetupObjectEventSprite paletteNum")

    # TrySetupObjectEventSprite reflection block
    eom, ok = _replace_once(eom,
        "    // DOWP: load palette on demand (replaces static slot pre-loading)\n"
        "    LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
        "\n"
        "    if (objectEvent->movementType == MOVEMENT_TYPE_INVISIBLE)",
        "    if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
        "        LoadPlayerObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "    else if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
        "        LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "\n"
        "\n"
        "    if (objectEvent->movementType == MOVEMENT_TYPE_INVISIBLE)", "")
    if ok:
        reverted.append("TrySetupObjectEventSprite: reflection pre-loading restored")
    else:
        failed.append("Could not restore TrySetupObjectEventSprite reflection block")

    # InitObjectEventPalettes
    eom, ok = _replace_once(eom,
        "void InitObjectEventPalettes(u8 palSlot)\n"
        "{\n"
        "    // DOWP: palettes load on demand — no bulk pre-loading.\n"
        "    FreeAndReserveObjectSpritePalettes();\n"
        "    gReservedSpritePaletteCount = 0; // All 16 OBJ slots available for dynamic use\n"
        "    sCurrentSpecialObjectPaletteTag = OBJ_EVENT_PAL_TAG_NONE;\n"
        "    sCurrentReflectionType = palSlot;\n"
        "}",
        "void InitObjectEventPalettes(u8 palSlot)\n"
        "{\n"
        "    FreeAndReserveObjectSpritePalettes();\n"
        "    sCurrentSpecialObjectPaletteTag = OBJ_EVENT_PAL_TAG_NONE;\n"
        "    sCurrentReflectionType = palSlot;\n"
        "    if (palSlot == 1)\n"
        "    {\n"
        "        PatchObjectPaletteRange(gObjectPaletteTagSets[sCurrentReflectionType], 0, 6);\n"
        "        gReservedSpritePaletteCount = 8;\n"
        "    }\n"
        "    else\n"
        "    {\n"
        "        PatchObjectPaletteRange(gObjectPaletteTagSets[sCurrentReflectionType], 0, 10);\n"
        "    }\n"
        "}", "")
    if ok:
        reverted.append("InitObjectEventPalettes: bulk loading restored")
    else:
        failed.append("Could not restore InitObjectEventPalettes")

    # RemoveObjectEventInternal
    eom, ok = _replace_once(eom,
        "static void RemoveObjectEventInternal(struct ObjectEvent *objectEvent)\n"
        "{\n"
        "    u8 paletteNum;\n"
        "    struct SpriteFrameImage image;\n"
        "    image.size = GetObjectEventGraphicsInfo(objectEvent->graphicsId)->size;\n"
        "    gSprites[objectEvent->spriteId].images = &image;\n"
        "    paletteNum = gSprites[objectEvent->spriteId].oam.paletteNum;\n"
        "    DestroySprite(&gSprites[objectEvent->spriteId]);\n"
        "    FieldEffectFreePaletteIfUnused(paletteNum);\n"
        "}",
        "static void RemoveObjectEventInternal(struct ObjectEvent *objectEvent)\n"
        "{\n"
        "    struct SpriteFrameImage image;\n"
        "    image.size = GetObjectEventGraphicsInfo(objectEvent->graphicsId)->size;\n"
        "    gSprites[objectEvent->spriteId].images = &image;\n"
        "    DestroySprite(&gSprites[objectEvent->spriteId]);\n"
        "}", "")
    if ok:
        reverted.append("RemoveObjectEventInternal: palette freeing removed")
    else:
        failed.append("Could not restore RemoveObjectEventInternal")

    # LoadObjectEventPalette def → static
    eom, ok = _replace_once(eom,
        "void LoadObjectEventPalette(u16 paletteTag)\n{",
        "static void LoadObjectEventPalette(u16 paletteTag)\n{", "")
    if ok:
        reverted.append("LoadObjectEventPalette: def restored to static")
    elif "static void LoadObjectEventPalette(u16 paletteTag)\n{" in eom:
        reverted.append("LoadObjectEventPalette: def already static")
    else:
        failed.append("Could not restore LoadObjectEventPalette def")

    # LoadObjectEventPalette decl → static
    eom, ok = _replace_once(eom,
        "void LoadObjectEventPalette(u16);",
        "static void LoadObjectEventPalette(u16);", "")
    if ok:
        reverted.append("LoadObjectEventPalette: decl restored to static")
    elif "static void LoadObjectEventPalette(u16);" in eom:
        reverted.append("LoadObjectEventPalette: decl already static")
    else:
        failed.append("Could not restore LoadObjectEventPalette decl")

    _write(eom_path, eom)

    # ── Remove marker file ────────────────────────────────────────────────────
    marker_path = os.path.join(project_root, MARKER_FILE)
    if os.path.isfile(marker_path):
        try:
            os.remove(marker_path)
            reverted.append("Marker file removed")
        except OSError as e:
            failed.append(f"Could not remove marker file: {e}")

    return len(failed) == 0, reverted, failed


def apply_dowp_patch(project_root: str,
                     tint_r: int = 5,
                     tint_g: int = 5,
                     tint_b: int = 10) -> Tuple[bool, List[str], List[str]]:
    """Apply the Dynamic Overworld Palettes patch.

    Returns:
        (success, applied_descriptions, failed_descriptions)
    """
    applied: List[str] = []
    failed: List[str] = []

    # ════════════════════════════════════════════════════════════════════════
    # 1. event_object_movement.c
    # ══════════════════════════════════════════��═════════════════════════════
    eom_path = os.path.join(project_root, "src", "event_object_movement.c")
    if not os.path.isfile(eom_path):
        return False, applied, ["event_object_movement.c not found"]

    eom = _read(eom_path)

    # 1a. Make LoadObjectEventPalette non-static (forward decl)
    eom, ok = _replace_once(eom,
        "static void LoadObjectEventPalette(u16);",
        "void LoadObjectEventPalette(u16);",
        "Make LoadObjectEventPalette non-static (decl)")
    if ok:
        applied.append("LoadObjectEventPalette: forward decl made non-static")
    else:
        # Maybe already non-static
        if "void LoadObjectEventPalette(u16);" in eom:
            applied.append("LoadObjectEventPalette: already non-static (decl)")
        else:
            failed.append("Could not find LoadObjectEventPalette forward decl")

    # 1b. Make LoadObjectEventPalette non-static (definition)
    eom, ok = _replace_once(eom,
        "static void LoadObjectEventPalette(u16 paletteTag)\n{",
        "void LoadObjectEventPalette(u16 paletteTag)\n{",
        "Make LoadObjectEventPalette non-static (def)")
    if ok:
        applied.append("LoadObjectEventPalette: definition made non-static")
    else:
        if "void LoadObjectEventPalette(u16 paletteTag)\n{" in eom:
            applied.append("LoadObjectEventPalette: already non-static (def)")
        else:
            failed.append("Could not find LoadObjectEventPalette definition")

    # 1c. Modify RemoveObjectEventInternal to free palette on destroy
    old_remove = (
        "static void RemoveObjectEventInternal(struct ObjectEvent *objectEvent)\n"
        "{\n"
        "    struct SpriteFrameImage image;\n"
        "    image.size = GetObjectEventGraphicsInfo(objectEvent->graphicsId)->size;\n"
        "    gSprites[objectEvent->spriteId].images = &image;\n"
        "    DestroySprite(&gSprites[objectEvent->spriteId]);\n"
        "}"
    )
    new_remove = (
        "static void RemoveObjectEventInternal(struct ObjectEvent *objectEvent)\n"
        "{\n"
        "    u8 paletteNum;\n"
        "    struct SpriteFrameImage image;\n"
        "    image.size = GetObjectEventGraphicsInfo(objectEvent->graphicsId)->size;\n"
        "    gSprites[objectEvent->spriteId].images = &image;\n"
        "    paletteNum = gSprites[objectEvent->spriteId].oam.paletteNum;\n"
        "    DestroySprite(&gSprites[objectEvent->spriteId]);\n"
        "    FieldEffectFreePaletteIfUnused(paletteNum);\n"
        "}"
    )
    eom, ok = _replace_once(eom, old_remove, new_remove,
        "RemoveObjectEventInternal: add palette freeing")
    if ok:
        applied.append("RemoveObjectEventInternal: palette freed on destroy")
    else:
        if "FieldEffectFreePaletteIfUnused(paletteNum);" in eom:
            applied.append("RemoveObjectEventInternal: already patched")
        else:
            failed.append("Could not patch RemoveObjectEventInternal")

    # 1d. Modify InitObjectEventPalettes — stop bulk-loading palettes
    old_init = (
        "void InitObjectEventPalettes(u8 palSlot)\n"
        "{\n"
        "    FreeAndReserveObjectSpritePalettes();\n"
        "    sCurrentSpecialObjectPaletteTag = OBJ_EVENT_PAL_TAG_NONE;\n"
        "    sCurrentReflectionType = palSlot;\n"
        "    if (palSlot == 1)\n"
        "    {\n"
        "        PatchObjectPaletteRange(gObjectPaletteTagSets[sCurrentReflectionType], 0, 6);\n"
        "        gReservedSpritePaletteCount = 8;\n"
        "    }\n"
        "    else\n"
        "    {\n"
        "        PatchObjectPaletteRange(gObjectPaletteTagSets[sCurrentReflectionType], 0, 10);\n"
        "    }\n"
        "}"
    )
    new_init = (
        "void InitObjectEventPalettes(u8 palSlot)\n"
        "{\n"
        "    // DOWP: palettes load on demand — no bulk pre-loading.\n"
        "    FreeAndReserveObjectSpritePalettes();\n"
        "    gReservedSpritePaletteCount = 0; // All 16 OBJ slots available for dynamic use\n"
        "    sCurrentSpecialObjectPaletteTag = OBJ_EVENT_PAL_TAG_NONE;\n"
        "    sCurrentReflectionType = palSlot;\n"
        "}"
    )
    eom, ok = _replace_once(eom, old_init, new_init,
        "InitObjectEventPalettes: remove bulk loading")
    if ok:
        applied.append("InitObjectEventPalettes: dynamic mode (no bulk pre-load)")
    else:
        if "// DOWP: palettes load on demand" in eom:
            applied.append("InitObjectEventPalettes: already patched")
        else:
            failed.append("Could not patch InitObjectEventPalettes")

    # 1e. TrySetupObjectEventSprite — replace reflection pre-loading
    #     and paletteNum assignment
    old_reflect_setup = (
        "    if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
        "        LoadPlayerObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "    else if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
        "        LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "\n"
        "\n"
        "    if (objectEvent->movementType == MOVEMENT_TYPE_INVISIBLE)"
    )
    new_reflect_setup = (
        "    // DOWP: load palette on demand (replaces static slot pre-loading)\n"
        "    LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
        "\n"
        "    if (objectEvent->movementType == MOVEMENT_TYPE_INVISIBLE)"
    )
    eom, ok = _replace_once(eom, old_reflect_setup, new_reflect_setup,
        "TrySetupObjectEventSprite: replace reflection pre-loading")
    if ok:
        applied.append("TrySetupObjectEventSprite: dynamic palette loading")
    else:
        failed.append("Could not patch TrySetupObjectEventSprite reflection block")

    # 1f. All 5 paletteNum assignment sites → use IndexOfSpritePaletteTag
    #     We do this as a targeted replacement for each unique context line.
    palette_sites = [
        # Site 1: TrySetupObjectEventSprite (after sprite creation)
        ("    sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
         "    sprite->coordOffsetEnabled = TRUE;\n"
         "    sprite->data[0] = objectEventId;\n"
         "    objectEvent->spriteId = spriteId;\n"
         "    // DEBUG — log object spawn position",
         "    sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
         "    sprite->coordOffsetEnabled = TRUE;\n"
         "    sprite->data[0] = objectEventId;\n"
         "    objectEvent->spriteId = spriteId;\n"
         "    // DEBUG — log object spawn position",
         "TrySetupObjectEventSprite paletteNum"),

        # Site 2: CreateVirtualObject
        ("        sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
         "        sprite->coordOffsetEnabled = TRUE;\n"
         "        sprite->sVirtualObjId = virtualObjId;\n"
         "        sprite->sVirtualObjElev = elevation;\n"
         "        if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
         "            LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);",
         "        LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
         "        sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
         "        sprite->coordOffsetEnabled = TRUE;\n"
         "        sprite->sVirtualObjId = virtualObjId;\n"
         "        sprite->sVirtualObjElev = elevation;",
         "CreateVirtualObject paletteNum"),

        # Site 3: CreateFameCheckerObject
        ("        sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
         "        sprite->data[0] = localId;\n"
         "        if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
         "            LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);",
         "        LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
         "        sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
         "        sprite->data[0] = localId;",
         "CreateFameCheckerObject paletteNum"),

        # Site 4: SpawnObjectEventOnReturnToField — reflection pre-load + paletteNum
        ("    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;\n"
         "    if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
         "        LoadPlayerObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
         "\n"
         "    if (graphicsInfo->paletteSlot >= PALSLOT_NPC_SPECIAL)\n"
         "        LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
         "\n"
         "    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;",
         "    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;\n"
         "    // DOWP: load palette on demand\n"
         "    LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
         "\n"
         "    *(u16 *)&spriteTemplate.paletteTag = TAG_NONE;",
         "SpawnObjectEventOnReturnToField reflection pre-load"),
    ]

    for old_site, new_site, desc in palette_sites:
        eom, ok = _replace_once(eom, old_site, new_site, desc)
        if ok:
            applied.append(f"{desc}: patched")
        else:
            failed.append(f"Could not patch {desc}")

    # Site 4 also needs paletteNum at its assignment line
    old_s4_pal = (
        "        sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
        "        sprite->coordOffsetEnabled = TRUE;\n"
        "        sprite->data[0] = objectEventId;\n"
        "        objectEvent->spriteId = spriteId;\n"
        "        // DEBUG — log return-to-field spawn"
    )
    new_s4_pal = (
        "        sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
        "        sprite->coordOffsetEnabled = TRUE;\n"
        "        sprite->data[0] = objectEventId;\n"
        "        objectEvent->spriteId = spriteId;\n"
        "        // DEBUG — log return-to-field spawn"
    )
    eom, ok = _replace_once(eom, old_s4_pal, new_s4_pal,
        "SpawnObjectEventOnReturnToField paletteNum")
    if ok:
        applied.append("SpawnObjectEventOnReturnToField paletteNum: patched")
    else:
        failed.append("Could not patch SpawnObjectEventOnReturnToField paletteNum")

    # Site 5: ObjectEventSetGraphicsId
    old_s5 = (
        "    if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
        "        PatchObjectPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "\n"
        "    if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
        "        LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, graphicsInfo->paletteSlot);\n"
        "    \n"
        "    var = sprite->images->size / TILE_SIZE_4BPP;"
    )
    new_s5 = (
        "    // DOWP: free old palette, load new one dynamically\n"
        "    {\n"
        "        u8 oldPalNum = sprite->oam.paletteNum;\n"
        "        LoadObjectEventPalette(graphicsInfo->paletteTag);\n"
        "        FieldEffectFreePaletteIfUnused(oldPalNum);\n"
        "    }\n"
        "    \n"
        "    var = sprite->images->size / TILE_SIZE_4BPP;"
    )
    eom, ok = _replace_once(eom, old_s5, new_s5,
        "ObjectEventSetGraphicsId palette handling")
    if ok:
        applied.append("ObjectEventSetGraphicsId: dynamic palette swap")
    else:
        failed.append("Could not patch ObjectEventSetGraphicsId")

    # Site 5 paletteNum
    old_s5_pal = (
        "    sprite->subspriteTables = graphicsInfo->subspriteTables;\n"
        "    sprite->oam.paletteNum = graphicsInfo->paletteSlot;\n"
        "    if (!sprite->usingSheet)"
    )
    new_s5_pal = (
        "    sprite->subspriteTables = graphicsInfo->subspriteTables;\n"
        "    sprite->oam.paletteNum = IndexOfSpritePaletteTag(graphicsInfo->paletteTag);\n"
        "    if (!sprite->usingSheet)"
    )
    eom, ok = _replace_once(eom, old_s5_pal, new_s5_pal,
        "ObjectEventSetGraphicsId paletteNum")
    if ok:
        applied.append("ObjectEventSetGraphicsId paletteNum: patched")
    else:
        failed.append("Could not patch ObjectEventSetGraphicsId paletteNum")

    _write(eom_path, eom)

    # ═════════════��═════════════════════════════════════��════════════════════
    # 2. field_effect.c — export FieldEffectFreePaletteIfUnused
    # ═══════════════════════════════════��════════════════════════════════════
    fe_path = os.path.join(project_root, "src", "field_effect.c")
    if os.path.isfile(fe_path):
        fe = _read(fe_path)

        # Forward decl: remove static
        fe, ok = _replace_once(fe,
            "static void FieldEffectFreePaletteIfUnused(u8 paletteNum);",
            "void FieldEffectFreePaletteIfUnused(u8 paletteNum);",
            "FieldEffectFreePaletteIfUnused: decl non-static")
        if ok:
            applied.append("FieldEffectFreePaletteIfUnused: decl made non-static")
        elif "void FieldEffectFreePaletteIfUnused(u8 paletteNum);" in fe:
            applied.append("FieldEffectFreePaletteIfUnused: decl already non-static")
        else:
            failed.append("Could not find FieldEffectFreePaletteIfUnused decl")

        # Definition: remove static
        fe, ok = _replace_once(fe,
            "static void FieldEffectFreePaletteIfUnused(u8 paletteNum)\n{",
            "void FieldEffectFreePaletteIfUnused(u8 paletteNum)\n{",
            "FieldEffectFreePaletteIfUnused: def non-static")
        if ok:
            applied.append("FieldEffectFreePaletteIfUnused: def made non-static")
        elif "void FieldEffectFreePaletteIfUnused(u8 paletteNum)\n{" in fe:
            applied.append("FieldEffectFreePaletteIfUnused: def already non-static")
        else:
            failed.append("Could not find FieldEffectFreePaletteIfUnused def")

        _write(fe_path, fe)
    else:
        failed.append("field_effect.c not found")

    # ══════════════════���════════════════════════════════��════════════════════
    # 3. field_effect.h — add FieldEffectFreePaletteIfUnused declaration
    # ════════════════════════════��═══════════════════════════════════════════
    feh_path = os.path.join(project_root, "include", "field_effect.h")
    if os.path.isfile(feh_path):
        feh = _read(feh_path)
        if "FieldEffectFreePaletteIfUnused" not in feh:
            # Add before the #endif
            feh = feh.rstrip()
            if feh.endswith("#endif"):
                feh = feh[:-6] + (
                    "// DOWP: exported for dynamic palette freeing\n"
                    "void FieldEffectFreePaletteIfUnused(u8 paletteNum);\n"
                    "\n#endif"
                )
                _write(feh_path, feh)
                applied.append("field_effect.h: added FieldEffectFreePaletteIfUnused decl")
            else:
                # Just append
                feh += "\n\n// DOWP: exported for dynamic palette freeing\nvoid FieldEffectFreePaletteIfUnused(u8 paletteNum);\n"
                _write(feh_path, feh)
                applied.append("field_effect.h: added FieldEffectFreePaletteIfUnused decl (appended)")
        else:
            applied.append("field_effect.h: FieldEffectFreePaletteIfUnused already declared")
    else:
        failed.append("field_effect.h not found")

    # ═════════════════════════════════════════════════���══════════════════════
    # 4. event_object_movement.h — add LoadObjectEventPalette declaration
    # ══════════════════════════════���═════════════════════════════════════��═══
    eomh_path = os.path.join(project_root, "include", "event_object_movement.h")
    if os.path.isfile(eomh_path):
        eomh = _read(eomh_path)
        if "void LoadObjectEventPalette" not in eomh:
            eomh = eomh.rstrip()
            if eomh.endswith("#endif"):
                eomh = eomh[:-6] + (
                    "// DOWP: dynamic palette loading\n"
                    "void LoadObjectEventPalette(u16 paletteTag);\n"
                    "\n#endif"
                )
            else:
                eomh += "\n\n// DOWP: dynamic palette loading\nvoid LoadObjectEventPalette(u16 paletteTag);\n"
            _write(eomh_path, eomh)
            applied.append("event_object_movement.h: added LoadObjectEventPalette decl")
        else:
            applied.append("event_object_movement.h: LoadObjectEventPalette already declared")
    else:
        failed.append("event_object_movement.h not found")

    # ═══════���══════════════════════════════════════════���══════════════════��══
    # 5. field_effect_helpers.c — dynamic reflection palettes
    # ══════════════════════════���══════════════════════════════���══════════════
    feh_c_path = os.path.join(project_root, "src", "field_effect_helpers.c")
    if os.path.isfile(feh_c_path):
        fehc = _read(feh_c_path)

        # Replace the gReflectionEffectPaletteMap usage in SetUpReflection
        old_refl_map = (
            "    reflectionSprite->oam.paletteNum = "
            "gReflectionEffectPaletteMap[reflectionSprite->oam.paletteNum];"
        )
        new_refl_map = (
            "    // DOWP: generate tinted reflection palette dynamically\n"
            "    {\n"
            "        u8 basePalNum = reflectionSprite->oam.paletteNum;\n"
            "        u16 basePalTag = GetSpritePaletteTagByPaletteNum(basePalNum);\n"
            "        u16 reflTag = basePalTag + 0x1000;\n"
            "        u8 reflSlot = IndexOfSpritePaletteTag(reflTag);\n"
            "        if (reflSlot == 0xFF)\n"
            "        {\n"
            "            u32 i;\n"
            "            u16 tintBuf[16];\n"
            "            struct SpritePalette reflPal;\n"
            "            CpuCopy16(&gPlttBufferUnfaded[OBJ_PLTT_ID(basePalNum)], tintBuf, PLTT_SIZE_4BPP);\n"
            "            for (i = 0; i < 16; i++)\n"
            "            {\n"
            "                u16 c = tintBuf[i];\n"
            f"                u32 r = (c & 0x1F) + {tint_r};\n"
            f"                u32 g = ((c >> 5) & 0x1F) + {tint_g};\n"
            f"                u32 b = ((c >> 10) & 0x1F) + {tint_b};\n"
            "                if (r > 31) r = 31;\n"
            "                if (g > 31) g = 31;\n"
            "                if (b > 31) b = 31;\n"
            "                tintBuf[i] = (u16)(r | (g << 5) | (b << 10));\n"
            "            }\n"
            "            reflPal.data = tintBuf;\n"
            "            reflPal.tag = reflTag;\n"
            "            reflSlot = LoadSpritePalette(&reflPal);\n"
            "        }\n"
            "        if (reflSlot != 0xFF)\n"
            "            reflectionSprite->oam.paletteNum = reflSlot;\n"
            "    }"
        )
        fehc, ok = _replace_once(fehc, old_refl_map, new_refl_map,
            "SetUpReflection: dynamic reflection palette")
        if ok:
            applied.append("SetUpReflection: dynamic reflection palette tinting")
        else:
            if "// DOWP: generate tinted reflection palette" in fehc:
                applied.append("SetUpReflection: already patched")
            else:
                failed.append("Could not patch SetUpReflection reflection palette")

        # Replace LoadObjectRegularReflectionPalette to use dynamic tinting
        old_regular_refl = (
            "static void LoadObjectRegularReflectionPalette(struct ObjectEvent * objectEvent, u8 paletteIndex)\n"
            "{\n"
            "    const struct ObjectEventGraphicsInfo * graphicsInfo;\n"
            "\n"
            "    graphicsInfo = GetObjectEventGraphicsInfo(objectEvent->graphicsId);\n"
            "    if (graphicsInfo->reflectionPaletteTag != OBJ_EVENT_PAL_TAG_NONE)\n"
            "    {\n"
            "        if (graphicsInfo->paletteSlot == PALSLOT_PLAYER)\n"
            "            LoadPlayerObjectReflectionPalette(graphicsInfo->paletteTag, paletteIndex);\n"
            "        else if (graphicsInfo->paletteSlot == PALSLOT_NPC_SPECIAL)\n"
            "            LoadSpecialObjectReflectionPalette(graphicsInfo->paletteTag, paletteIndex);\n"
            "        else\n"
            "            PatchObjectPalette(GetObjectPaletteTag(paletteIndex), paletteIndex);\n"
            "        UpdateSpritePaletteWithWeather(paletteIndex);\n"
            "    }\n"
            "}"
        )
        new_regular_refl = (
            "static void LoadObjectRegularReflectionPalette(struct ObjectEvent * objectEvent, u8 paletteIndex)\n"
            "{\n"
            "    // DOWP: reflection palettes are now generated dynamically in SetUpReflection.\n"
            "    // This function just ensures weather tinting is applied.\n"
            "    const struct ObjectEventGraphicsInfo * graphicsInfo;\n"
            "\n"
            "    graphicsInfo = GetObjectEventGraphicsInfo(objectEvent->graphicsId);\n"
            "    if (graphicsInfo->reflectionPaletteTag != OBJ_EVENT_PAL_TAG_NONE)\n"
            "    {\n"
            "        UpdateSpritePaletteWithWeather(paletteIndex);\n"
            "    }\n"
            "}"
        )
        fehc, ok = _replace_once(fehc, old_regular_refl, new_regular_refl,
            "LoadObjectRegularReflectionPalette: simplify for DOWP")
        if ok:
            applied.append("LoadObjectRegularReflectionPalette: simplified for DOWP")
        else:
            if "// DOWP: reflection palettes are now generated dynamically" in fehc:
                applied.append("LoadObjectRegularReflectionPalette: already patched")
            else:
                failed.append("Could not patch LoadObjectRegularReflectionPalette")

        _write(feh_c_path, fehc)
    else:
        failed.append("field_effect_helpers.c not found")

    # ════════════════════════════════════════════════════���═══════════════════
    # 6. Write marker file
    # ════════════════════════════════════════════════════════════════════════
    marker_path = os.path.join(project_root, MARKER_FILE)
    with open(marker_path, "w") as f:
        f.write(
            "Dynamic Overworld Palettes (DOWP) enabled by PorySuite-Z.\n"
            "This file marks that the DOWP patch has been applied to this project.\n"
            "Do not delete — PorySuite-Z uses this to detect patch status.\n"
        )
    applied.append("Marker file written")

    success = len(failed) == 0
    return success, applied, failed
