"""Innate abilities engine installer (PorySuite-Z).

The battle engine's ``BattlerHasAbility()`` already loops ``NUM_INNATE_SLOTS`` slots
via ``GetBattlerInnate()`` — but the accessor ships as a stub returning
``ABILITY_NONE``, so nothing has innates. This module supplies the missing DATA
source and wires the accessor to it:

* ``src/data/innate_abilities.h`` — a per-species ``gSpeciesInnates`` table
  (``[NUM_SPECIES][NUM_INNATE_SLOTS]``). PorySuite's species codegen (re)writes the
  CONTENT of this file; the installer only lays a valid empty default so the build
  works before the user assigns anything.
* ``GetBattlerInnate()`` is rewritten to read the battler's LIVE species' row (so
  innates follow form changes for free), with a bounds guard.

Everything is gated on ``supports_innates()`` — the project must already have the
innate check infrastructure (``NUM_INNATE_SLOTS`` + a ``GetBattlerInnate`` definition,
which the wider ability port installs). A vanilla decomp without that chokepoint is
left completely untouched. Idempotent: re-running changes nothing.
"""

import os
import re
import logging

_log = logging.getLogger(__name__)
_re_num_slots = re.compile(r"#define\s+NUM_INNATE_SLOTS\s+(\d+)")


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _write_if_changed(path, text):
    """Write only when content differs. Returns True if the file was written."""
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == text:
                return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return True


# ── detection ──────────────────────────────────────────────────────────────────
def supports_innates(project_root):
    """True if the project has the innate-check infrastructure the data system plugs
    into: ``NUM_INNATE_SLOTS`` in pokemon.h AND a ``GetBattlerInnate`` definition in
    battle_util.c. This is also what PorySuite's UI keys on to show the innate-
    assignment section — a vanilla decomp returns False and gets no innate UI."""
    ph = os.path.join(project_root, "include", "pokemon.h")
    bu = os.path.join(project_root, "src", "battle_util.c")
    return (os.path.isfile(ph) and "NUM_INNATE_SLOTS" in _read(ph)
            and os.path.isfile(bu) and "GetBattlerInnate" in _read(bu))


# ── the per-species data table (default = everyone has none) ─────────────────────
INNATE_TABLE_REL = os.path.join("src", "data", "innate_abilities.h")
INNATE_TABLE_INCLUDE = '#include "data/innate_abilities.h"'
INNATE_ARRAY = "gSpeciesInnates"

_TABLE_HEADER = (
    "// PorySuite-Z: per-species innate abilities - extra passive abilities a species\n"
    "// has IN ADDITION to its main ability (up to NUM_INNATE_SLOTS). GENERATED by\n"
    "// PorySuite; hand edits are overwritten on the next save. Only BASE species have\n"
    "// rows; alternate forms inherit their base's row via GetBattlerInnate(). A species\n"
    "// with no row (or ABILITY_NONE in a slot) simply has no innate there. Read through\n"
    "// GetBattlerInnate() -> BattlerHasAbility(), so innates apply everywhere the main\n"
    "// ability does.\n"
)


def render_innate_table(rows, slots=None):
    """Render the full innate_abilities.h text. *rows* maps a SPECIES_* constant name
    (str) -> list of ABILITY_* names (str). *slots* is the project's NUM_INNATE_SLOTS,
    used as a hard ceiling so a mis-sized row can never overflow the C array's
    [NUM_INNATE_SLOTS] dimension; falls back to _MAX_SLOTS_HINT when unknown. Empty /
    all-NONE rows are omitted (the table default covers them). An empty table renders a
    valid ``{0}``. The array is ``static const`` (internal linkage) so this header can
    only ever have one definition — it is #included in exactly one TU (battle_util.c)."""
    cap = slots if isinstance(slots, int) and slots > 0 else _MAX_SLOTS_HINT
    body_lines = []
    for species in sorted(rows):
        clean = [a for a in (rows.get(species) or []) if a and a != "ABILITY_NONE"]
        if not clean:
            continue
        clean = clean[:cap]
        inner = ", ".join(clean)
        body_lines.append("    [{}] = {{ {} }},".format(species, inner))
    if body_lines:
        init = "{\n" + "\n".join(body_lines) + "\n}"
    else:
        init = "{0}"
    return (_TABLE_HEADER
            + "static const u16 " + INNATE_ARRAY
            + "[NUM_SPECIES][NUM_INNATE_SLOTS] =\n" + init + ";\n")


# Fallback slot ceiling when the project's real NUM_INNATE_SLOTS wasn't supplied.
_MAX_SLOTS_HINT = 3


_re_form_const = re.compile(r"#define\s+(SPECIES_\w+)\s+\(\s*NUM_SPECIES\s*\+", re.M)


def form_species_consts(project_root):
    """Set of SPECIES_* consts that are ALTERNATE FORMS — those defined as
    ``(NUM_SPECIES + N)`` in species.h, so their numeric id is >= NUM_SPECIES.

    The innate codegen must skip these: the table is sized ``[NUM_SPECIES]``, so a
    ``[SPECIES_FORM] = {...}`` designated initializer for a form id would overflow the
    array and break the build. Forms don't need a row anyway — GetBattlerInnate keys on
    the BASE species, so a form inherits its base's row at runtime. Keyed on the
    DEFINITION rather than on extractor form-relocation, so a relocation miss on an
    unusual project can never leak a form const into the table."""
    sp = os.path.join(project_root, "include", "constants", "species.h")
    try:
        return set(_re_form_const.findall(_read(sp)))
    except Exception:
        return set()


def get_num_innate_slots(project_root, default=3):
    """Read NUM_INNATE_SLOTS from the project's pokemon.h so callers cap rows to the
    engine's real slot count. Returns *default* if it can't be found."""
    ph = os.path.join(project_root, "include", "pokemon.h")
    try:
        m = _re_num_slots.search(_read(ph))
        if m:
            return int(m.group(1))
    except Exception:
        pass
    return default


def write_default_table_if_absent(project_root):
    """Create src/data/innate_abilities.h with an empty (all-none) table if it does
    not already exist, so the engine compiles before any innate is assigned. Does NOT
    overwrite an existing table (that belongs to the codegen). Returns True if written."""
    path = os.path.join(project_root, INNATE_TABLE_REL)
    if os.path.isfile(path):
        return False
    return _write_if_changed(path, render_innate_table({}))


# ── accessor rewrite ─────────────────────────────────────────────────────────────
# Matched on the STABLE function shape (signature + canonical stub body), not on any
# preceding comment — so it works whatever project installed the stub. The replacement
# folds in the data-table include (placed right where the stub was, so every constant
# it references — NUM_SPECIES, NUM_INNATE_SLOTS, ABILITY_* — is already in scope) plus a
# correct comment, and the wired accessor.
_STUB_ANCHOR = (
    "u16 GetBattlerInnate(u8 battler, u32 slot)\n"
    "{\n"
    "    (void)battler;\n"
    "    (void)slot;\n"
    "    return ABILITY_NONE;\n"
    "}\n")
_ACCESSOR_HOOKED = (
    "// PorySuite-Z: per-species innate ability data (generated by PorySuite).\n"
    + INNATE_TABLE_INCLUDE + "\n\n"
    "// Innate abilities accessor (ability port): the battler's innate at *slot*. Innates\n"
    "// are intrinsic to the mon, so we key on its BASE species (formSpeciesIdTable[0]) —\n"
    "// every alternate-form id here is >= NUM_SPECIES, so keying on the live form would\n"
    "// find no row and the mon would lose all innates whenever it morphed. Keying on the\n"
    "// base makes forms inherit the base's innates. ABILITY_NONE for an empty / out-of-\n"
    "// range slot; routed through BattlerHasAbility so innates apply everywhere.\n"
    "u16 GetBattlerInnate(u8 battler, u32 slot)\n"
    "{\n"
    "    u16 species = gBattleMons[battler].species;\n"
    "    const u16 *forms = gSpeciesInfo[species].formSpeciesIdTable;\n"
    "    if (forms != NULL)\n"
    "        species = forms[0];   // innates live on the base form; forms inherit them\n"
    "    if (slot >= NUM_INNATE_SLOTS || species >= NUM_SPECIES)\n"
    "        return ABILITY_NONE;\n"
    "    return " + INNATE_ARRAY + "[species][slot];\n"
    "}\n")
# Best-effort removal of the stub's own "not wired yet" descriptive comment so it does
# not contradict the wired accessor (No-Dead-Code). Fires only if that exact block is
# present; a project whose stub has a different / no comment is unaffected.
_STUB_COMMENT = (
    "// Ability port (innate-ready): a battler's innate abilities (extra passives beyond\n"
    "// the main ability). Storage table is NOT wired yet — returns ABILITY_NONE so\n"
    "// BattlerHasAbility behaves exactly like a single-ability check for now. When the\n"
    "// innate data lands, only this accessor changes and innates work everywhere.\n")


def _wire_accessor(project_root):
    """Rewrite the GetBattlerInnate stub to read gSpeciesInnates, include the data
    table just above it, and drop the stub's now-false descriptive comment. Idempotent
    (skips if already wired). Returns True if changed."""
    bu = os.path.join(project_root, "src", "battle_util.c")
    if not os.path.isfile(bu):
        return False
    text = _read(bu)
    if INNATE_ARRAY in text:      # already wired
        return False
    if _STUB_ANCHOR not in text:
        _log.warning("innate patch: GetBattlerInnate stub not found in the expected "
                     "shape — accessor NOT wired (innates stay inert).")
        return False
    text = text.replace(_STUB_COMMENT, "", 1)              # best-effort stale-comment drop
    text = text.replace(_STUB_ANCHOR, _ACCESSOR_HOOKED, 1)
    return _write_if_changed(bu, text)


def apply_innate_system(project_root):
    """Install the innate DATA system into *project_root* (accessor + default table).
    No-op on a project without the innate infrastructure. Idempotent. Returns a dict
    of what changed. The table CONTENT is owned by PorySuite's species codegen; this
    only guarantees a compiling default and the wired accessor."""
    if not supports_innates(project_root):
        _log.info("innate patch: project has no innate infrastructure "
                  "(NUM_INNATE_SLOTS / GetBattlerInnate) — skipping.")
        return {"supported": False}
    return {
        "supported": True,
        "default_table": write_default_table_if_absent(project_root),
        "accessor_wired": _wire_accessor(project_root),
    }
