"""Detect whether a generated header is produced by the project's OWN build
(jsonproc / AUTO_GEN_TARGETS).

PorySuite must never hand-write such a file. The build regenerates it from the
.json source of truth (via the engine's own jsonproc + Inja template), so a
hand-written copy can drift from the template (e.g. drop custom-pocket items),
AND stamping the header's mtime >= the .json's makes ``make`` treat it as
up-to-date and SKIP the regeneration — compiling the stale/wrong header.

Locations are DISCOVERED by scanning the project's makefiles, so this stays
project-agnostic (a fork that keeps the rule in a non-standard .mk still
resolves; an old fork that genuinely lacks the rule returns False so the caller
can fall back to writing it).
"""
import glob
import os
import re

__all__ = ["is_autogenerated_header"]


def is_autogenerated_header(root: str, header_basename: str) -> bool:
    """True if any project makefile declares *header_basename* (e.g. ``items.h``)
    as a build target generated from a like-named ``.json`` (a jsonproc rule) or
    lists it in ``AUTO_GEN_TARGETS``.
    """
    if not root or not header_basename:
        return False
    stem = re.escape(os.path.splitext(header_basename)[0])
    base = re.escape(header_basename)
    # e.g.  $(DATA_SRC_SUBDIR)/items.h: $(DATA_SRC_SUBDIR)/items.json ...
    rule_re = re.compile(rf"{stem}\.h\s*:.*\b{stem}\.json")
    # e.g.  AUTO_GEN_TARGETS += $(DATA_SRC_SUBDIR)/items.h
    autogen_re = re.compile(rf"AUTO_GEN_TARGETS\s*\+=.*\b{base}\b")
    candidates = glob.glob(os.path.join(root, "*.mk")) + [os.path.join(root, "Makefile")]
    for mk in candidates:
        try:
            with open(mk, encoding="utf-8", errors="ignore") as f:
                txt = f.read()
        except OSError:
            continue
        if rule_re.search(txt) or autogen_re.search(txt):
            return True
    return False
