"""Engine patcher for time-of-day wild encounters.

Installs the runtime scaffolding so the per-phase encounter tables the editor
saves to `wild_encounters.json` actually drive the game. Additive and
idempotent — a second run is a no-op, and on a project with no time-aware maps
the ROM is byte-identical to an unpatched build (the template output doesn't
move, and the engine branch is dormant).

What it installs
================
- `src/data/wild_encounters.json.txt` (REPLACED, guarded): the encounter
  codegen template, extended to expand a `time_of_day` array into N per-phase
  tables + N consecutive headers. Proven to produce byte-identical output to the
  stock template for every non-time map, so replacing it is safe.
- `src/data/wild_encounters_tod_slots.h` (GENERATED): the phase→slot map, as
  designated initialisers keyed by the project's own phase enum, plus
  `WILD_TOD_PHASE_COUNT`. Regenerated from the capability each apply.
- `src/wild_encounter.c` (MODIFIED, two PORYSUITE-TOD-guarded edits): include
  the slot header; and, in `GetCurrentMapWildMonHeaderId`, an `else if` to the
  Altering-Cave branch that offsets the header index by the current phase's slot
  when the map has consecutive same-map headers.

The design mirrors the Altering Cave (`i += index`), which is why no separate
"time-aware maps" table is needed: a time-aware map is detected structurally by
its consecutive same-map headers, and Altering Cave keeps its own branch first
so the two never collide.
"""

from __future__ import annotations

import os

from core.time_of_day import TimeOfDayCapability

_RES = os.path.join(os.path.dirname(__file__), "resources",
                    "wild_encounters_tod.json.txt")

_SLOT_HEADER_REL = os.path.join("src", "data", "wild_encounters_tod_slots.h")
_TEMPLATE_REL = os.path.join("src", "data", "wild_encounters.json.txt")
_ENGINE_REL = os.path.join("src", "wild_encounter.c")

_TOD_MARKER = "time_of_day"          # present in the patched template
_INCLUDE_MARK = "wild_encounters_tod_slots.h"
_BRANCH_MARK = "PORYSUITE-TOD-BEGIN"

# --- the two wild_encounter.c edits, as exact anchored replacements ---------

_INCLUDE_ANCHOR = '#include "data/wild_encounters.h"'
_INCLUDE_NEW = (
    '#include "data/wild_encounters.h"\n'
    '#include "data/wild_encounters_tod_slots.h"  // PORYSUITE-TOD')

_BRANCH_ANCHOR = (
    "                i += alteringCaveId;\n"
    "            }\n"
    "\n"
    "            if (!UnlockedTanobyOrAreNotInTanoby())")
_BRANCH_NEW = (
    "                i += alteringCaveId;\n"
    "            }\n"
    "            // PORYSUITE-TOD-BEGIN  time-of-day encounter table select\n"
    "            else if (gWildMonHeaders[i + 1].mapGroup == wildHeader->mapGroup &&\n"
    "                     gWildMonHeaders[i + 1].mapNum == wildHeader->mapNum)\n"
    "            {\n"
    "                u8 todPhase = PorySuite_GetTimeOfDay();\n"
    "                u8 todSlot = (todPhase < TIME_PHASE_COUNT) ? sWildTodSlot[todPhase] : 0;\n"
    "                if (todSlot >= WILD_TOD_PHASE_COUNT)\n"
    "                    todSlot = 0;\n"
    "                i += todSlot;\n"
    "            }\n"
    "            // PORYSUITE-TOD-END\n"
    "\n"
    "            if (!UnlockedTanobyOrAreNotInTanoby())")


class TodPatchError(Exception):
    pass


def _read(path: str) -> str:
    with open(path, encoding="utf-8", errors="surrogateescape") as fh:
        return fh.read()


def _write(path: str, text: str) -> None:
    tmp = path + ".todtmp"
    with open(tmp, "w", encoding="utf-8", errors="surrogateescape",
              newline="\n") as fh:
        fh.write(text)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)


def build_slot_header(cap: TimeOfDayCapability) -> str:
    """The generated phase→slot header text, from the project's own phases.

    Designated initialisers keyed by the phase enum make the mapping robust to
    the enum's ordering and gaps: `[TIME_NIGHT] = 2` says night reads the third
    table regardless of the fact that TIME_NIGHT's enum value is 3. Inactive
    phases (never returned) are simply absent and default to 0.
    """
    if not cap.present:
        raise TodPatchError("project has no time-of-day system")
    lines = [
        "// Generated by PorySuite-Z. DO NOT EDIT.",
        "// Time-of-day wild-encounter phase -> table-slot map. Each time-aware",
        "// map emits its per-phase tables in slot order (0..N-1); this maps the",
        "// value PorySuite_GetTimeOfDay() returns to that slot.",
        "#ifndef GUARD_WILD_ENCOUNTERS_TOD_SLOTS_H",
        "#define GUARD_WILD_ENCOUNTERS_TOD_SLOTS_H",
        "",
        '#include "%s"' % os.path.basename(cap.source_header or "time_of_day.h"),
        "",
        "#define WILD_TOD_PHASE_COUNT %d" % cap.slot_count,
        "",
        "static const u8 sWildTodSlot[] = {",
    ]
    for ph in cap.active_phases:
        lines.append("    [%s] = %d," % (ph.name, ph.slot))
    lines += ["};", "", "#endif // GUARD_WILD_ENCOUNTERS_TOD_SLOTS_H", ""]
    return "\n".join(lines)


def is_applied(project_dir: str) -> bool:
    """True if all three pieces are already installed."""
    tmpl = os.path.join(project_dir, _TEMPLATE_REL)
    eng = os.path.join(project_dir, _ENGINE_REL)
    slot = os.path.join(project_dir, _SLOT_HEADER_REL)
    try:
        return (_TOD_MARKER in _read(tmpl)
                and os.path.isfile(slot)
                and _BRANCH_MARK in _read(eng))
    except OSError:
        return False


def apply(project_dir: str, cap: TimeOfDayCapability) -> bool:
    """Install/refresh the scaffolding. Returns True if anything was written.

    Idempotent: the template and engine edits are guarded by their markers; the
    slot header is regenerated (it's cheap and must track the phase config).
    Raises TodPatchError if the project isn't time-capable or an engine anchor
    can't be found (rather than writing a half-patch).
    """
    if not cap.present:
        raise TodPatchError("project has no time-of-day system; nothing to do")

    wrote = False

    # 1. slot header — always (re)written; it must match the current phases.
    slot_path = os.path.join(project_dir, _SLOT_HEADER_REL)
    slot_text = build_slot_header(cap)
    if not os.path.isfile(slot_path) or _read(slot_path) != slot_text:
        _write(slot_path, slot_text)
        wrote = True

    # 2. template — replace with the tod-capable one, unless already patched.
    tmpl_path = os.path.join(project_dir, _TEMPLATE_REL)
    tmpl_text = _read(tmpl_path)
    if _TOD_MARKER not in tmpl_text:
        _write(tmpl_path, _read(_RES))
        wrote = True

    # 3. engine — two guarded edits.
    eng_path = os.path.join(project_dir, _ENGINE_REL)
    eng = _read(eng_path)
    changed = False
    if _INCLUDE_MARK not in eng:
        if _INCLUDE_ANCHOR not in eng:
            raise TodPatchError(
                "could not find the wild_encounters.h include in "
                "src/wild_encounter.c to anchor the slot-header include")
        eng = eng.replace(_INCLUDE_ANCHOR, _INCLUDE_NEW, 1)
        changed = True
    if _BRANCH_MARK not in eng:
        if _BRANCH_ANCHOR not in eng:
            raise TodPatchError(
                "could not find the Altering-Cave block in "
                "GetCurrentMapWildMonHeaderId to anchor the time-of-day branch")
        eng = eng.replace(_BRANCH_ANCHOR, _BRANCH_NEW, 1)
        changed = True
    if changed:
        _write(eng_path, eng)
        wrote = True

    return wrote
