#!/usr/bin/env python3
"""Generate the engine's name->pointer tables from a pokefirered project.

Scans the project's battle-anim C for every GLOBAL sprite template
(`const struct SpriteTemplate gXxx = ...`) and every GLOBAL task function
(`void AnimTask_Xxx(u8 ...)`), and emits:

  - gen_tables.c : extern decls + `gHostTemplates[]` / `gHostTasks[]` arrays the
    driver indexes into (so Python can request any sprite/task by index).
  - names.json   : {"templates": [...], "tasks": [...]} so the Python driver maps
    a template/task NAME (from the parsed script) to its index.

This is the dynamic bridge: whatever templates/tasks the project defines become
addressable. Run as part of the build pipeline (P2).
"""

from __future__ import annotations

import json
import os
import re
import sys

# Scalar global sprite templates only (arrays `gXxx[] =` are indexed elsewhere,
# never by a script's createsprite).
_TPL = re.compile(r"^const\s+struct\s+SpriteTemplate\s+(g[A-Za-z0-9_]+)\s*=", re.M)
# Global task functions (static ones are file-local, never createvisualtask'd).
_TASK = re.compile(r"^void\s+(AnimTask_[A-Za-z0-9_]+)\s*\(\s*u8", re.M)

_SRC_GLOBS = ("battle_anim", "sprite")


def _scan(src_dir: str):
    templates, tasks = [], []
    seen_t, seen_k = set(), set()
    for fn in sorted(os.listdir(src_dir)):
        if not fn.endswith(".c"):
            continue
        if not any(fn == f"{g}.c" or fn.startswith(f"{g}_") or fn.startswith("battle_anim")
                   for g in _SRC_GLOBS):
            continue
        text = open(os.path.join(src_dir, fn), encoding="utf-8", errors="replace").read()
        for m in _TPL.finditer(text):
            n = m.group(1)
            if n not in seen_t:
                seen_t.add(n); templates.append(n)
        for m in _TASK.finditer(text):
            n = m.group(1)
            if n not in seen_k:
                seen_k.add(n); tasks.append(n)
    return templates, tasks


def generate(project_root: str, out_dir: str):
    src_dir = os.path.join(project_root, "src")
    templates, tasks = _scan(src_dir)

    lines = [
        "/* AUTO-GENERATED by gen_tables.py — name->pointer tables for the host",
        " * animation engine. Indexes match names.json so Python can request any",
        " * template/task the project defines. Do not edit by hand. */",
        '#include "global.h"',
        '#include "sprite.h"',
        "",
        "typedef void (*HostTaskFn)(u8);",
        "",
    ]
    for n in templates:
        lines.append(f"extern const struct SpriteTemplate {n};")
    lines.append("")
    for n in tasks:
        lines.append(f"extern void {n}(u8);")
    lines.append("")
    lines.append("const struct SpriteTemplate *const gHostTemplates[] = {")
    for n in templates:
        lines.append(f"    &{n},")
    lines.append("};")
    lines.append(f"const int gHostTemplateCount = {len(templates)};")
    lines.append("")
    lines.append("HostTaskFn const gHostTasks[] = {")
    for n in tasks:
        lines.append(f"    {n},")
    lines.append("};")
    lines.append(f"const int gHostTaskCount = {len(tasks)};")
    lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "gen_tables.c"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    with open(os.path.join(out_dir, "names.json"), "w", encoding="utf-8") as f:
        json.dump({"templates": templates, "tasks": tasks}, f, indent=0)

    return len(templates), len(tasks)


if __name__ == "__main__":
    proj = sys.argv[1] if len(sys.argv) > 1 else "pokefirered"
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join("enginehost", "buildwasm")
    nt, nk = generate(proj, out)
    print(f"templates={nt} tasks={nk} -> {out}/gen_tables.c + names.json")
