import os
import sys
import io
import json
import threading
import glob
from contextlib import redirect_stdout
from abc import ABC, abstractmethod
from typing import Type
from pathlib import PureWindowsPath, PurePosixPath

from PyQt6.QtGui import QImage, QPixmap
import logging

from plugin_abstract.pokemon_data_extractor import PokemonDataExtractor
from local_env import LocalUtil


class MissingSourceError(RuntimeError):
    """Raised when canonical source files required for write-back are missing."""

    def __init__(self, missing: list[str]):
        deduped = sorted({os.path.normpath(path) for path in missing})
        self.missing = deduped
        super().__init__("Missing canonical source files")


class ReadSourceFile(object):
    """
    A context manager for reading a source file.

    Uses the project_info dictionary to determine the absolute path to the file.
    The provided ``file_path`` may be relative to the project's root or an
    absolute path; absolute paths are normalised to be relative to the project
    root so the same API can be used on all platforms.

    Args:
        project_info (dict): A dictionary containing project information.
        file_path (str): The path to the file to be read. Can be absolute or
            relative to the project root.

    Usage:
        with ReadSourceFile(project_info, file_path) as file:
            # Perform operations on the file
    """

    def __init__(self, project_info: dict, file_path: str):
        util = LocalUtil(project_info)
        self.docker_util = None
        root = util.repo_root()

        normalized = os.path.normpath(file_path)
        if os.path.isabs(normalized):
            normalized = os.path.relpath(normalized, root)

        if sys.platform == "win32":
            self.docker_util = util
            temp_path = os.path.join(project_info["dir"], "temp")
            os.makedirs(temp_path, exist_ok=True)
            try:
                import ctypes
                ctypes.windll.kernel32.SetFileAttributesW(temp_path, 0x02)  # FILE_ATTRIBUTE_HIDDEN
            except Exception:
                pass
            self.file_path = os.path.join(temp_path, normalized)
            os.makedirs(PureWindowsPath(self.file_path).parent, exist_ok=True)
            self.docker_util.copy_file_to_host(normalized, self.file_path)
        else:
            self.file_path = os.path.join(root, normalized)

    def __enter__(self):
        self.file = open(self.file_path, "r", encoding="utf-8")
        return self.file

    def __exit__(self, *args):
        self.file.close()


class WriteSourceFile(object):
    """A context manager for writing project sources without introducing new files."""

    def __init__(self, project_info: dict, file_path: str, *, insert_header: bool = False, require_existing: bool = True):
        util = LocalUtil(project_info)
        self.docker_util = None
        self.insert_header = insert_header
        self.require_existing = require_existing
        root = util.repo_root()

        normalized = os.path.normpath(file_path)
        if os.path.isabs(normalized):
            normalized = os.path.relpath(normalized, root)

        if sys.platform == "win32":
            self.docker_util = util
        self.file_path = os.path.join(root, normalized)

        if self.require_existing and not os.path.exists(self.file_path):
            raise FileNotFoundError(f"Expected source file missing: {self.file_path}")

    def __enter__(self):
        parent_dir = os.path.dirname(self.file_path)
        if parent_dir and not os.path.exists(parent_dir):
            os.makedirs(parent_dir, exist_ok=True)
        if self.docker_util is not None:
            self.file = io.StringIO()
        else:
            self.file = open(self.file_path, "w", encoding="utf-8", newline="\n")
        if self.insert_header:
            self.file.write("// *** IMPORTANT ***\n")
            self.file.write("// This file was generated by PorySuite.\n")
            self.file.write("// Any changes made to this file will be lost when recompiling the project.\n\n")
        return self.file

    def __exit__(self, *args):
        if self.docker_util is not None:
            self.docker_util.write_file_to_volume(self.file, self.file_path)
        else:
            self.file.close()


class ParseThread(threading.Thread):
    def __init__(self, data_class: "AbstractPokemonData"):
        super().__init__()
        self.data_class = data_class
        self.exception: BaseException | None = None

    def run(self):
        try:
            if self.data_class.should_parse_to_c_code():
                self.data_class.parse_to_c_code()
        except Exception as exc:
            self.exception = exc


class AbstractPokemonData(ABC):
    """
    Abstract base class for Pokémon data.

    This class provides methods for extracting, saving, and parsing Pokémon data.

    All data is stored in a JSON file in the 'src/data' directory. The filename is
    determined by the `DATA_FILE` attribute.

    Attributes:
        DATA_FILE (str): The name of the exported JSON file.
        FILES (dict): A dictionary of files used for extracting data.
        GENERATED_FILES (dict): A dictionary of generated files to be deleted after compiling.
        EXTRACTOR (PokemonDataExtractor): The data extractor.
        project_info (dict): The project information dictionary.
        parent (AbstractPokemonData): The parent object.
        data (dict): The Pokémon data.
        original_data (dict): The original Pokémon data.
        pending_changes (bool): Whether or not there are pending changes.
    """
    DATA_FILE: str = None
    # Instance attributes `FILES` and `GENERATED_FILES` are created in
    # ``__init__`` so each instance maintains its own dictionaries.
    EXTRACTOR: PokemonDataExtractor = None
    SOURCE_PREFIX: str = "source/"

    def __init__(self, project_info: dict, parent=None):
        self.project_info = project_info
        self.parent = parent
        self.FILES = {}
        self.GENERATED_FILES = {}
        self._in_memory_backups: dict[str, str] = {}
        self.data = None
        self.original_data = None
        self.pending_changes = False
        if "source_prefix" not in self.project_info:
            prefix = getattr(parent, "SOURCE_PREFIX", self.SOURCE_PREFIX)
            self.project_info["source_prefix"] = prefix
        self.docker_util = LocalUtil(self.project_info)

    def default_data(self):
        """Return an empty structure appropriate for this data file."""
        if self.DATA_FILE == "starters.json":
            return []
        if self.DATA_FILE == "moves.json":
            return {"moves": {}, "move_descriptions": {}, "constants": {}}
        if self.DATA_FILE == "pokedex.json":
            return {"national_dex": [], "regional_dex": []}
        return {}

    def __load_data(self) -> bool:
        """Load JSON data if available and fall back to defaults."""

        json_path = None
        if self.DATA_FILE is not None:
            json_path = os.path.join(
                self.project_info["dir"], "src", "data", self.DATA_FILE
            )

        if json_path and os.path.isfile(json_path):
            try:
                with open(json_path, encoding="utf-8") as f:
                    self.data = json.load(f)
                    self.original_data = json.loads(json.dumps(self.data))
                return True
            except (FileNotFoundError, json.decoder.JSONDecodeError):
                pass

        self.data = self.default_data()
        self.original_data = json.loads(json.dumps(self.data))
        return False
    
    def __get_file_paths(self, file_key: str) -> tuple[str, str]:
        """
        Gets the original and backup file paths for a given file key.
        
        Args:
            file_key (str): The key of the file in the FILES dictionary.
            
        Returns:
            tuple[str, str]: A tuple containing the original and backup file paths respectively.
        """
        original = f"{self.FILES[file_key]['original']}"
        backup = f"{self.FILES[file_key]['backup']}"
        return original, backup

    def instantiate_extractor(self, func: callable):
        """
        Takes the extractors constructor and instantiates it as self.EXTRACTOR

        Args:
            func (callable): The extractor's constructor method.
        """
        self.EXTRACTOR = func(self.project_info, self.DATA_FILE, self.FILES)
        loaded = self.__load_data()
        should_extract = (
            self.EXTRACTOR is not None and self.EXTRACTOR.should_extract()
        )
        if self.EXTRACTOR is not None and (not loaded or should_extract):
            if getattr(self, "logger", None):
                buf = io.StringIO()
                with redirect_stdout(buf):
                    extracted = self.EXTRACTOR.extract_data()
                    if extracted:
                        self.data = extracted
                        self.original_data = json.loads(json.dumps(self.data))
                        self.save()
                output = buf.getvalue().strip()
                if output:
                    for line in output.splitlines():
                        self.logger(line)
            else:
                extracted = self.EXTRACTOR.extract_data()
                if extracted:
                    self.data = extracted
                    self.original_data = json.loads(json.dumps(self.data))
                    self.save()

    def get_data(self) -> dict:
        return self.data

    def get_file_path(self, file_key: str, use_backup: bool = False) -> str:
        if use_backup:
            return self.FILES[file_key]["backup"]
        return self.FILES[file_key]["original"]

    def get_generated_file_path(self, file_key: str) -> str:
        return self.GENERATED_FILES[file_key]

    def add_file_to_backup(self, file_path: str, file_key: str):
        """
        Adds a file to the backup dictionary.

        Args:
            file_path (str): The path of the file to be added to the backup.
            file_key (str): The key to be used for the file in the backup dictionary.
        """
        if file_key not in self.FILES:
            prefix = self.project_info.get("source_prefix", self.SOURCE_PREFIX)
            if prefix:
                file_path = os.path.join(prefix, file_path)
            normalized = os.path.normpath(file_path)
            backup_rel = os.path.normpath(os.path.join('temp', 'porysuite', 'backups', normalized))
            self.FILES[file_key] = {
                "original": normalized,
                "backup": backup_rel,
            }
        else:
            raise ValueError(f"Key {file_key} already exists in the files dictionary.")

    def add_generated_file(self, file_path: str, file_key: str):
        """
        Adds a generated file to the list of files to be deleted after compiling.

        Args:
            file_path (str): The file path starting from the project's source directory.
            file_key (str): The key to use for retrieving the file path.
        """
        if file_key not in self.GENERATED_FILES:
            prefix = self.project_info.get("source_prefix", self.SOURCE_PREFIX)
            if prefix:
                file_path = os.path.join(prefix, file_path)
            self.GENERATED_FILES[file_key] = file_path
        else:
            raise ValueError(f"Key {file_key} already exists in the generated files dictionary.")

    def missing_required_sources(self) -> list[str]:
        """Return absolute paths for canonical sources that are missing on disk."""

        missing: list[str] = []
        root = self.docker_util.repo_root()
        for info in self.FILES.values():
            original = info.get("original")
            if not original:
                continue
            abs_path = os.path.join(root, os.path.normpath(original))
            if not os.path.isfile(abs_path):
                missing.append(abs_path)
        return missing

    def save(self):
        """
        Save the data to a JSON file.

        If the `DATA_FILE` attribute is not None and either the data has been modified
        or the file does not exist, the data is saved to a JSON file. The file path is
        determined by the `project_info` attribute.
        """
        if self.DATA_FILE is not None:
            # Check if the data has been modified or the file does not exist
            should_save = self.original_data is not None and self.data != self.original_data
            file_path = os.path.join(
                self.project_info["dir"], "src", "data", self.DATA_FILE
            )
            if not os.path.isfile(file_path) or should_save:
                if not self.data:
                    print("Error: refusing to overwrite with empty data")
                    return
                # Convert the data to a JSON string with indentation
                json_str = json.dumps(self.data, indent=4)
                # Write the JSON string to the file
                with open(file_path, 'w', encoding="utf-8", newline="\n") as json_file:
                    json_file.write(json_str)
                # Update the original data and set pending changes flag
                self.original_data = json.loads(json_str)
                self.pending_changes = True
                print(f"Saved {self.DATA_FILE} file.")

    def should_parse_to_c_code(self) -> bool:
        """
        Checks if the data should be parsed into C code.

        Returns:
            bool: True if the data should be parsed into C code, False otherwise.
        """
        if not self.data or not self.original_data:
            return False

        return self.pending_changes

    def try_parse_to_c_code(self):
        """
        Tries to parse the source files to C code.
        If an exception occurs, it attempts to use backup files and parse again.
        """
        try:
            self.parse_to_c_code()
        except Exception as e:
            print(f"Error parsing source files for {self.DATA_FILE}: {e}")
            print("Attempting to use backup files...")
            self.restore_source_code()
            self.parse_to_c_code()
            pass

    @abstractmethod
    def parse_to_c_code(self):
        """
        An abstract method for parsing the source files to C code.

        This method should be overridden by subclasses to parse the source files to C code. Always call the
        superclass method first to ensure that the original source files are backed up before making changes.

        If the data has been modified, it saves the changes. For each file, if a backup file doesn't exist,
        it copies the original file to create one.

        After completing these operations, it sets the `pending_changes` flag to False.
        """
        if self.data != self.original_data:
            self.save()

        root = self.docker_util.repo_root()
        for file in self.FILES:
            original, _ = self.__get_file_paths(file)
            original_path = os.path.join(root, original)
            if os.path.isfile(original_path):
                with open(original_path, "r", encoding="utf-8") as handle:
                    self._in_memory_backups[original] = handle.read()
            else:
                logging.warning("Original file %s missing; skipping backup", original)

        self.pending_changes = False

    def restore_source_code(self):
        root = self.docker_util.repo_root()
        for file in self.FILES:
            original, _ = self.__get_file_paths(file)
            content = self._in_memory_backups.get(original)
            if content is None:
                continue
            original_path = os.path.join(root, original)
            parent_dir = os.path.dirname(original_path)
            if parent_dir and not os.path.exists(parent_dir):
                os.makedirs(parent_dir, exist_ok=True)
            with open(original_path, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
        self._in_memory_backups.clear()
        prefix = self.project_info.get("source_prefix", self.SOURCE_PREFIX)
        for file in self.GENERATED_FILES:
            path = self.GENERATED_FILES[file]
            if prefix:
                path = os.path.join(prefix, path)
            if self.docker_util.file_exists(path):
                self.docker_util.removefile(path)


class SpeciesData(AbstractPokemonData, ABC):
    """
    A class representing species data for Pokemon.

    This class provides methods to retrieve and manipulate species data.

    All data is stored in 'species.json' in the 'src/data' directory.

    Args:
        project_info (dict): Information about the project.
        parent (Optional): The parent object.

    Attributes:
        DATA_FILE (str): The name of the data file.

    """

    DATA_FILE = "species.json"

    def __init__(self, project_info: dict, parent=None):
        """
        Initializes a new instance of the SpeciesData class.

        Args:
            project_info (dict): Information about the project.
            parent (Optional): The parent object.

        """
        super().__init__(project_info, parent)

    def get_species(self, species: str, form: str = None) -> dict | None:
        """
        Retrieves the dictionary data for a specific species.

        Args:
            species (str): The name of the species.
            form (str, optional): The name of the form.

        Returns:
            dict | None: The data for the species, or None if not found.

        """
        if species in self.data:
            if form is not None and form in self.data[species]["forms"]:
                return self.data[species]["forms"][form]
            return self.data[species]
        return None

    def get_species_data(self, species: str, key: str, form: str = None) -> str | int | dict | list | None:
        """
        Retrieves a specific piece of data for a species.

        Args:
            species (str): The name of the species.
            key (str): The key of the data to retrieve.
            form (str, optional): The name of the form.

        Returns:
            str | int | dict | list | None: The value of the data, or None if not found.

        """
        try:
            if form is None or key == "dex_num":
                value = self.data[species][key]
            else:
                value = self.data[species]["forms"][form][key]
        except KeyError:
            value = None
        return value

    @abstractmethod
    def get_species_info(self, species: str, key: str,
                         form: str = None, index: int = None) -> str | int | dict | list | None:
        """
        Retrieves additional information for a species.

        This method should be implemented by subclasses.

        Args:
            species (str): The name of the species.
            key (str): The key of the information to retrieve.
            form (int, optional): The name of the form.
            index (int, optional: The index of the information.

        Returns:
            str | int | dict | list | None: The additional information, or None if not found.

        """
        pass

    @abstractmethod
    def set_species_info(self, species: str, key: str, value: str | int | dict | list, form: str = None):
        """
        Sets additional information for a species.

        This method should be implemented by subclasses.

        Args:
            species (str): The name of the species.
            key (str): The key of the information to set.
            value (str | int | dict | list): The value of the information.
            form (str, optional): The name of the form.

        """
        pass

    @abstractmethod
    def get_species_ability(self, species: str, ability_index: int, form: str = None) -> str:
        """
        Retrieves the ability of a species.

        This method should be implemented by subclasses.

        Args:
            species (str): The name of the species.
            ability_index (int): The index of the ability.
            form (str, optional): The name of the form.

        Returns:
            str: The ability of the species.

        """
        pass

    @abstractmethod
    def species_info_key_exists(self, species: str, key: str, form: str = None) -> bool:
        """
        Checks if a specific key exists in the species information.

        This method should be implemented by subclasses.

        Args:
            species (str): The name of the species.
            key (str): The key to check.
            form (str, optional): The name of the form.

        Returns:
            bool: True if the key exists, False otherwise.

        """
        pass

    @abstractmethod
    def parse_species_info(self, species_name: str, form_name: str = None) -> str:
        """
        Parses the species information.

        This method should be implemented by subclasses.

        Args:
            species_name (str): The name of the species.
            form_name (str, optional): The name of the form.

        Returns:
            str: The parsed species information.

        """
        pass


class SpeciesGraphics(AbstractPokemonData, ABC):
    """
    A class representing the graphics data for a species of Pokemon.

    This class provides methods to retrieve and manipulate images associated with a Pokemon species.

    All data is stored in 'species_graphics.json' in the 'src/data' directory.

    Attributes:
        DATA_FILE (str): The name of the data file containing the species graphics information.

    Args:
        project_info (dict): A dictionary containing project information.
        parent (Optional): The parent object. Defaults to None.
    """

    DATA_FILE = "species_graphics.json"

    def __init__(self, project_info: dict, parent=None):
        """
        Initializes a new instance of the SpeciesGraphics class.

        Args:
            project_info (dict): A dictionary containing project information.
            parent (Optional): The parent object. Defaults to None.
        """
        super().__init__(project_info, parent)
        self.project_dir = project_info["dir"]

    def get_image(self, key, index=-1) -> QPixmap | None:
        """
        Retrieves the image associated with the specified key.

        Args:
            key (str): The key of the image to retrieve.
            index (int, optional): The index of the frame to retrieve. Defaults to -1.

        Returns:
            QPixmap | None: The retrieved image as a QPixmap object, or None if the image is not found.
        """
        if key in self.data:
            img_data = self.data[key]
            if "png" in img_data:
                prefix = self.project_info.get("source_prefix", self.SOURCE_PREFIX)
                path = os.path.join(self.project_dir, prefix, img_data["png"]) if prefix else os.path.join(self.project_dir, img_data["png"])
                if os.path.exists(path):
                    img = QImage(path)
                    if index == -1:
                        return QPixmap.fromImage(img)
                    else:
                        # Get the image size
                        width = img.width()
                        # Calculate the frame size
                        frame_width = width
                        frame_height = width
                        # Calculate the frame offset
                        frame_offset = index * frame_height
                        # Create a new image
                        new_img = QImage(img.width(), img.height(), QImage.Format_ARGB32)
                        # Copy the frame from the original image to the new image
                        new_img.fill(0)
                        for y in range(frame_height):
                            for x in range(frame_width):
                                new_img.setPixelColor(x, y, img.pixelColor(x, y + frame_offset))
                        return QPixmap.fromImage(new_img)
        return None


class PokemonAbilities(AbstractPokemonData, ABC):
    """
    A class representing the data for Pokémon abilities.

    This class provides functionality for managing and accessing abilities data.

    All data is stored in 'abilities.json' in the 'src/data' directory.

    Attributes:
        DATA_FILE (str): The name of the JSON file containing abilities data.
    """
    DATA_FILE = "abilities.json"


class PokemonItems(AbstractPokemonData, ABC):
    """
    A class representing the data for Pokémon items.
    
    This class provides functionality for managing and accessing items data.

    All data is stored in 'items.json' in the 'src/data' directory.

    Attributes:
        DATA_FILE (str): The name of the data file containing the items information.
    """
    DATA_FILE = "items.json"


class PokemonEvolutions(AbstractPokemonData, ABC):
    """A class representing Pokémon evolution data."""

    DATA_FILE = "evolutions.json"


class PokemonConstants(AbstractPokemonData, ABC):
    """
    A class representing the data for important game constants.
    
    This class provides functionality for managing and accessing game constants data.
    
    All data is stored in 'constants.json' in the 'src/data' directory.
    
    Attributes:
        DATA_FILE (str): The name of the data file containing the constants information.
    """
    DATA_FILE = "constants.json"


class PokemonStarters(AbstractPokemonData, ABC):
    """
    A class representing the data for the starter Pokémon.
    
    This class provides functionality for managing and accessing starter Pokémon data.
    
    All data is stored in 'starters.json' in the 'src/data' directory.
    
    Attributes:
        DATA_FILE (str): The name of the data file containing the starters information.
    """
    DATA_FILE = "starters.json"


class PokemonMoves(AbstractPokemonData, ABC):
    """
    A class representing the data for Pokémon moves.

    This class provides functionality for managing and accessing moves data.

    All data is stored in 'moves.json' in the 'src/data' directory.

    Attributes:
        DATA_FILE (str): The name of the data file containing the moves information.
    """
    DATA_FILE = "moves.json"


class PokemonTrainers(AbstractPokemonData, ABC):
    """Data class representing trainer definitions."""

    DATA_FILE = "trainers.json"


class Pokedex(AbstractPokemonData, ABC):
    """
    A class representing the data for the Pokédex.

    This class provides functionality for managing and accessing Pokédex data.

    All data is stored in 'pokedex.json' in the 'src/data' directory.

    Attributes:
        DATA_FILE (str): The name of the data file containing the Pokédex information.
    """
    DATA_FILE = "pokedex.json"


class PokemonDataManager(ABC):
    """
    A class that manages game data for a PorySuite project.

    This class provides methods to add, retrieve, and manipulate various types of game data, such as species data,
    graphics, abilities, items, constants, starters, moves, and Pokédex information.

    The `PokemonDataManager` class serves as a central hub for accessing and modifying different types of Pokemon data
    within a project.
    """
    SOURCE_PREFIX = AbstractPokemonData.SOURCE_PREFIX

    def __init__(self, project_info: dict, logger=None):
        self.logger = logger

        def init_body():
            self.project_info = dict(project_info)
            if "source_prefix" not in self.project_info:
                self.project_info["source_prefix"] = self.SOURCE_PREFIX
            util = LocalUtil(self.project_info)
            resolved = util.repo_root()
            if resolved != self.project_info.get("dir"):
                if not (
                    os.path.isdir(os.path.join(resolved, "src"))
                    and os.path.isdir(os.path.join(resolved, "include"))
                ):
                    raise RuntimeError(
                        "Resolved repo_root does not contain required folders: "
                        f"{resolved}"
                    )
                print(
                    f"repo_root mismatch: selected {self.project_info.get('dir')} resolved {resolved}"
                )
            else:
                print(f"repo_root confirmed: {resolved}")
            self.data = {}

        if self.logger:
            buf = io.StringIO()
            with redirect_stdout(buf):
                init_body()
            output = buf.getvalue().strip()
            if output:
                for line in output.splitlines():
                    self.logger(line)
        else:
            init_body()
        
    def __add_data_class(self, class_obj: Type, key: str):
        instance = class_obj(self.project_info, self)
        if instance.data is None:
            instance.data = instance.default_data() if hasattr(instance, "default_data") else {}
        self.data[key] = instance

    def add_species_data_class(self, class_obj: Type[SpeciesData]):
        self.__add_data_class(class_obj, "species_data")

    def add_species_graphics_class(self, class_obj: Type[SpeciesGraphics]):
        self.__add_data_class(class_obj, "species_graphics")

    def add_pokemon_abilities_class(self, class_obj: Type[PokemonAbilities]):
        self.__add_data_class(class_obj, "pokemon_abilities")

    def add_pokemon_items_class(self, class_obj: Type[PokemonItems]):
        self.__add_data_class(class_obj, "pokemon_items")

    def add_pokemon_evolutions_class(self, class_obj: Type[PokemonEvolutions]):
        self.__add_data_class(class_obj, "pokemon_evolutions")

    def add_pokemon_constants_class(self, class_obj: Type[PokemonConstants]):
        self.__add_data_class(class_obj, "pokemon_constants")
    
    def add_pokemon_starters_class(self, class_obj: Type[PokemonStarters]):
        self.__add_data_class(class_obj, "pokemon_starters")

    def add_pokemon_moves_class(self, class_obj: Type[PokemonMoves]):
        self.__add_data_class(class_obj, "pokemon_moves")

    def add_pokemon_trainers_class(self, class_obj: Type[PokemonTrainers]):
        self.__add_data_class(class_obj, "pokemon_trainers")

    def add_pokedex_class(self, class_obj: Type[Pokedex]):
        self.__add_data_class(class_obj, "pokedex")

    def save(self):
        missing = self.missing_required_sources()
        if missing:
            raise MissingSourceError(missing)
        for data in self.data:
            self.data[data].save()

    def parse_to_c_code(self):
        missing = self.missing_required_sources()
        if missing:
            raise MissingSourceError(missing)
        threads = []
        for data in self.data:
            thread = ParseThread(self.data[data])
            threads.append(thread)
            thread.start()
        # Poll with a short timeout so Qt's event loop keeps running.
        # A plain thread.join() blocks the main thread indefinitely and causes
        # Windows to mark the window as "Not Responding".
        try:
            from PyQt6.QtWidgets import QApplication
            from PyQt6.QtCore import QEventLoop
            _pump = lambda: QApplication.processEvents(
                QEventLoop.ProcessEventsFlag.ExcludeUserInputEvents
            )
        except Exception:
            _pump = lambda: None
        for thread in threads:
            while thread.is_alive():
                thread.join(timeout=0.05)
                _pump()
        for thread in threads:
            if thread.exception is not None:
                raise thread.exception

    def restore_source_code(self):
        for data in self.data:
            self.data[data].restore_source_code()

    def missing_required_sources(self) -> list[str]:
        missing: list[str] = []
        for data_obj in self.data.values():
            try:
                missing.extend(data_obj.missing_required_sources())
            except Exception:
                continue
        deduped: list[str] = []
        seen: set[str] = set()
        for path in missing:
            norm = os.path.normpath(path)
            if norm not in seen:
                seen.add(norm)
                deduped.append(norm)
        return deduped

    def get_pokemon_data(self) -> dict:
        return self.data["species_data"].data

    def get_species(self, species: str, form: str = None) -> dict | None:
        return self.data["species_data"].get_species(species, form)

    def get_species_by_dex_constant(self, dex_constant: str) -> str | None:
        # Prefer national_dex (kept current by rename operations) over species_data
        # whose dex_constant field can lag after a rename.
        for entry in self.get_national_dex():
            if entry.get("dex_constant") == dex_constant:
                return entry.get("species")
        for species in self.data["species_data"].data:
            if self.data["species_data"].data[species].get("dex_constant") == dex_constant:
                return species
        return None

    def get_species_data(self, species: str, key: str, form: str = None) -> str | int | dict | list | None:
        return self.data["species_data"].get_species_data(species, key, form)

    def get_species_info(self, species: str, key: str, form: str = None):
        return self.data["species_data"].get_species_info(species, key, form)

    def set_species_info(self, species: str, key: str, value, form: str = None):
        self.data["species_data"].set_species_info(species, key, value, form)

    def get_species_ability(self, species: str, ability_index: int, form: str = None):
        return self.data["species_data"].get_species_ability(species, ability_index, form)

    def get_species_image(self, species: str, key: str, index: int = -1, form: str = None):
        image_name = self.get_species_info(species, key, form)
        sg = self.data.get("species_graphics")
        if not sg or not sg.data or image_name is None:
            return None
        return sg.get_image(image_name, index)

    def get_species_image_path(self, species: str, key: str, form: str = None) -> str | None:
        image_name = self.get_species_info(species, key, form)
        sg = self.data.get("species_graphics")
        if not sg or not sg.data or image_name is None:
            return None
        if image_name not in sg.data:
            logging.warning("Image '%s' missing from species_graphics", image_name)
            return None
        image_url = sg.data[image_name]["png"]
        prefix = self.project_info.get("source_prefix", self.SOURCE_PREFIX)
        path = os.path.join(
            self.project_info["dir"], prefix, image_url
        ) if prefix else os.path.join(self.project_info["dir"], image_url)
        if not os.path.isfile(path):
            logging.warning("Image file '%s' not found", path)
            return None
        from PyQt6.QtCore import QUrl
        return QUrl.fromLocalFile(path).toString()

    def species_info_key_exists(self, species: str, key: str, form: str = None) -> bool:
        return self.data["species_data"].species_info_key_exists(species, key, form)

    def get_pokemon_abilities(self) -> dict:
        pa = self.data.get("pokemon_abilities")
        if pa and pa.data:
            return pa.data
        return {}

    def get_ability(self, ability: str) -> dict:
        return self.get_pokemon_abilities().get(ability, {})

    def get_ability_by_id(self, ability_id: int) -> dict:
        abilities = self.get_pokemon_abilities()
        for ability in abilities:
            if abilities[ability]["id"] == ability_id:
                return ability

    def get_ability_data(self, ability: str, key: str) -> str | int:
        return self.get_ability(ability).get(key)

    def get_ability_data_by_id(self, ability_id: int, key: str) -> str | int:
        abilities = self.get_pokemon_abilities()
        for ability in abilities:
            if abilities[ability]["id"] == ability_id:
                return abilities[ability].get(key)

    def get_pokemon_items(self) -> dict:
        pi = self.data.get("pokemon_items")
        if pi and pi.data:
            return pi.data
        return {}

    def get_item(self, item: str) -> dict:
        items = self.get_pokemon_items()
        if isinstance(items, list):
            for entry in items:
                if isinstance(entry, dict):
                    if str(entry.get("id")) == str(item) or entry.get("constant") == item:
                        return entry
            return {}
        return items.get(item, {})

    def get_item_data(self, item: str, key: str) -> str | int | None:
        item_data = self.get_item(item)
        if isinstance(item_data, dict):
            return item_data.get(key)
        return None

    def get_pokemon_constants(self) -> dict:
        pc = self.data.get("pokemon_constants")
        if pc and pc.data:
            return pc.data
        return {}

    def get_constant(self, constant: str) -> dict | str | int:
        return self.get_pokemon_constants().get(constant)

    def get_constant_data(self, constant: str, key: str) -> str | int:
        const = self.get_constant(constant)
        if isinstance(const, dict):
            return const.get(key)
        return const

    def get_pokemon_starters(self) -> dict:
        ps = self.data.get("pokemon_starters")
        if ps and ps.data:
            return ps.data
        return []

    def get_starter(self, index: int) -> dict:
        starters = self.get_pokemon_starters()
        if index < len(starters):
            return starters[index]
        return {}

    def get_starter_data(self, index: int, key: str) -> str | int:
        starter = self.get_starter(index)
        return starter.get(key)

    def set_starter_data(self, index: int, key: str, value: str | int):
        starters = self.get_pokemon_starters()
        while len(starters) <= index:
            starters.append({})
        starters[index][key] = value

    def get_evolutions(self, species: str) -> list:
        pe = self.data.get("pokemon_evolutions")
        if pe and pe.data is not None:
            json_path = os.path.join(
                self.project_info["dir"], "src", "data", pe.DATA_FILE
            )
            if os.path.isfile(json_path):
                return pe.data.get(species, [])
        return self.get_species_info(species, "evolutions") or []

    def set_evolutions(self, species: str, evolutions: list):
        pe = self.data.get("pokemon_evolutions")
        if pe and pe.data is not None:
            json_path = os.path.join(
                self.project_info["dir"], "src", "data", pe.DATA_FILE
            )
            if os.path.isfile(json_path):
                pe.data[species] = evolutions
                return
        self.set_species_info(species, "evolutions", evolutions)

    def get_species_moves(self, species: str) -> list:
        pm = self.data.get("pokemon_moves")
        if pm and pm.data:
            return pm.data.get("species_moves", {}).get(species, [])
        return []

    def set_species_moves(self, species: str, moves: list):
        pm = self.data.get("pokemon_moves")
        if pm and pm.data is not None:
            pm.data.setdefault("species_moves", {})[species] = moves

    def get_pokemon_moves(self) -> dict:
        pm = self.data.get("pokemon_moves")
        if pm and pm.data:
            return pm.data.get("moves", {})
        return {}

    def get_move(self, move: str) -> dict:
        return self.get_pokemon_moves().get(move, {})

    def get_move_data(self, move: str, key: str) -> str | int:
        return self.get_move(move).get(key)

    def get_move_description(self, move: str) -> str:
        pm = self.data.get("pokemon_moves")
        if not pm or not pm.data:
            return ""
        # Prefer direct mapping by move constant when available
        descs = pm.data.get("move_descriptions", {})
        if move in descs:
            return descs.get(move) or ""
        # Fallback: some plugins store a variable name in the move struct
        move_data = pm.data.get("moves", {}).get(move, {})
        desc_var = move_data.get("description_var")
        if isinstance(desc_var, str):
            return descs.get(desc_var, "")
        return ""

    def set_move_data(self, move: str, key: str, value: str | int | bool):
        pm = self.data.get("pokemon_moves")
        if pm and pm.data:
            pm.data.setdefault("moves", {}).setdefault(move, {})[key] = value

    def get_pokemon_trainers(self) -> dict:
        pt = self.data.get("pokemon_trainers")
        if pt and pt.data:
            return pt.data
        return {}

    def get_trainer(self, trainer: str) -> dict:
        return self.get_pokemon_trainers().get(trainer, {})

    def get_trainer_data(self, trainer: str, key: str):
        return self.get_trainer(trainer).get(key)

    def set_trainer_data(self, trainer: str, key: str, value):
        trainers = self.get_pokemon_trainers()
        trainers.setdefault(trainer, {})[key] = value

    def get_national_dex(self) -> list:
        dex = self.data.get("pokedex")
        if dex and dex.data:
            return dex.data.get("national_dex", [])
        return []

    def get_regional_dex(self) -> list:
        dex = self.data.get("pokedex")
        if dex and dex.data:
            return dex.data.get("regional_dex", [])
        return []

    def clear_caches(self):
        """Delete all ``src/data`` JSON files for this project.

        Uses ``project_info["dir"]`` directly (same path used by ``save()``)
        so the clear and the save always target the same directory.
        Returns the number of files removed.
        """
        root = self.project_info.get("dir", "")
        cleared = 0
        for path in glob.glob(os.path.join(root, "src", "data", "*.json")):
            try:
                os.remove(path)
                cleared += 1
            except OSError:
                pass
        return cleared

    def rebuild_caches(self, logger=None):
        """Re-extract all data from C headers and rewrite JSON cache files.

        Each extractor runs independently — a failure in one does not abort
        the others.  Progress and errors are surfaced through ``logger``.
        """
        cleared = self.clear_caches()
        if logger:
            logger(f"Cleared {cleared} cached file(s). Re-extracting from source headers...")

        failed = []
        skipped = []
        for key, data_obj in self.data.items():
            extractor = getattr(data_obj, "EXTRACTOR", None)
            if extractor is None:
                skipped.append(key)
                continue
            if logger:
                logger(f"Extracting {key}...")
            extractor.reset_cache()
            buf = io.StringIO()
            result = None
            try:
                with redirect_stdout(buf):
                    result = extractor.extract_data()
            except Exception as exc:
                failed.append((key, str(exc)))
                if logger:
                    logger(f"  ERROR extracting {key}: {exc}")
            output = buf.getvalue().strip()
            if logger and output:
                for line in output.splitlines():
                    logger(f"  {line}")
            if result:
                data_obj.data = result
                data_obj.original_data = json.loads(json.dumps(result))
                data_obj.save()
            else:
                if logger and extractor is not None and key not in [f for f, _ in failed]:
                    logger(f"  WARNING: {key} returned no data — tab may be empty")

        if skipped and logger:
            logger(f"Skipped (no extractor): {', '.join(skipped)}")
        if failed and logger:
            logger(f"Rebuild finished with {len(failed)} error(s): "
                   + ", ".join(k for k, _ in failed))
