# Form implementation generated from reading ui file 'ui/exporting.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Exporting(object):
    def setupUi(self, Exporting):
        Exporting.setObjectName("Exporting")
        Exporting.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Exporting.resize(480, 160)
        Exporting.setMinimumSize(QtCore.QSize(480, 160))
        Exporting.setMaximumSize(QtCore.QSize(480, 160))
        Exporting.setModal(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Exporting)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Exporting)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(parent=Exporting)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(Exporting)
        QtCore.QMetaObject.connectSlotsByName(Exporting)

    def retranslateUi(self, Exporting):
        _translate = QtCore.QCoreApplication.translate
        Exporting.setWindowTitle(_translate("Exporting", "Exporting"))
        self.label.setText(_translate("Exporting", "Building ROM..."))
