# Form implementation generated from reading ui file 'ui/loadingproject.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadingProject(object):
    def setupUi(self, LoadingProject):
        LoadingProject.setObjectName("LoadingProject")
        LoadingProject.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        LoadingProject.resize(500, 150)
        LoadingProject.setWindowTitle("PorySuite-Z")
        LoadingProject.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadingProject)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(40, 20, 40, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=LoadingProject)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(parent=LoadingProject)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LoadingProject)
        QtCore.QMetaObject.connectSlotsByName(LoadingProject)

    def retranslateUi(self, LoadingProject):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("LoadingProject", "Loading Project"))
