# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ui.custom_widgets.deselectabletreewidget import DeselectableTreeWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(986, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setDocumentMode(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(2)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setHandleWidth(16)
        self.splitter.setObjectName("splitter")
        self.mainBox = QtWidgets.QGroupBox(parent=self.splitter)
        self.mainBox.setTitle("")
        self.mainBox.setFlat(False)
        self.mainBox.setObjectName("mainBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mainTabs = QtWidgets.QTabWidget(parent=self.mainBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mainTabs.sizePolicy().hasHeightForWidth())
        self.mainTabs.setSizePolicy(sizePolicy)
        self.mainTabs.setMinimumSize(QtCore.QSize(0, 0))
        self.mainTabs.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.mainTabs.setUsesScrollButtons(False)
        self.mainTabs.setDocumentMode(True)
        self.mainTabs.setObjectName("mainTabs")
        self.tab_pokemon = QtWidgets.QWidget()
        self.tab_pokemon.setObjectName("tab_pokemon")
        self.tab_pokemon_grid = QtWidgets.QGridLayout(self.tab_pokemon)
        self.tab_pokemon_grid.setObjectName("tab_pokemon_grid")
        self.tab_pokemon_data = QtWidgets.QTabWidget(parent=self.tab_pokemon)
        self.tab_pokemon_data.setObjectName("tab_pokemon_data")
        self.tab_pokemon_info = QtWidgets.QWidget()
        self.tab_pokemon_info.setObjectName("tab_pokemon_info")
        self.tab_pokemon_info_grid = QtWidgets.QGridLayout(self.tab_pokemon_info)
        self.tab_pokemon_info_grid.setObjectName("tab_pokemon_info_grid")
        self.verticalLayout_pokemon_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_pokemon_info.setObjectName("verticalLayout_pokemon_info")
        self.label_32 = QtWidgets.QLabel(parent=self.tab_pokemon_info)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_pokemon_info.addWidget(self.label_32)
        self.species_flags = QtWidgets.QListWidget(parent=self.tab_pokemon_info)
        self.species_flags.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded
        )
        self.species_flags.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )
        self.species_flags.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.species_flags.setProperty("showDropIndicator", False)
        self.species_flags.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.species_flags.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.species_flags.setObjectName("species_flags")
        for _ in range(8):
            item = QtWidgets.QListWidgetItem()
            item.setCheckState(QtCore.Qt.CheckState.Unchecked)
            self.species_flags.addItem(item)
        self.verticalLayout_pokemon_info.addWidget(self.species_flags)
        self.tab_pokemon_info_grid.addLayout(
            self.verticalLayout_pokemon_info, 0, 1, 1, 1
        )
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_22 = QtWidgets.QLabel(parent=self.tab_pokemon_info)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_22
        )
        self.species_name = QtWidgets.QLineEdit(parent=self.tab_pokemon_info)
        self.species_name.setMaxLength(10)
        self.species_name.setObjectName("species_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.species_name
        )
        self.label_29 = QtWidgets.QLabel(parent=self.tab_pokemon_info)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_29
        )
        self.dex_num = QtWidgets.QLabel(parent=self.tab_pokemon_info)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dex_num.sizePolicy().hasHeightForWidth())
        self.dex_num.setSizePolicy(sizePolicy)
        self.dex_num.setMinimumSize(QtCore.QSize(0, 0))
        self.dex_num.setSizeIncrement(QtCore.QSize(0, 0))
        self.dex_num.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.dex_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dex_num.setObjectName("dex_num")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dex_num
        )
        self.label_30 = QtWidgets.QLabel(parent=self.tab_pokemon_info)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_30
        )
        self.species_category = QtWidgets.QLineEdit(parent=self.tab_pokemon_info)
        self.species_category.setMaxLength(11)  # u8 categoryName[12] null-terminated = 11 usable chars
        self.species_category.setObjectName("species_category")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.species_category
        )
        self.label_31 = QtWidgets.QLabel(parent=self.tab_pokemon_info)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_31
        )
        self.species_description = QtWidgets.QPlainTextEdit(
            parent=self.tab_pokemon_info
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.species_description.sizePolicy().hasHeightForWidth()
        )
        self.species_description.setSizePolicy(sizePolicy)
        self.species_description.setMinimumSize(QtCore.QSize(330, 70))
        self.species_description.setMaximumSize(QtCore.QSize(330, 70))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.species_description.setFont(font)
        self.species_description.setTabChangesFocus(True)
        self.species_description.setUndoRedoEnabled(False)
        self.species_description.setLineWrapMode(
            QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap
        )
        self.species_description.setMaximumBlockCount(0)
        self.species_description.setBackgroundVisible(False)
        self.species_description.setObjectName("species_description")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.species_description
        )
        self.tab_pokemon_info_grid.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tab_pokemon_data.addTab(self.tab_pokemon_info, "")
        self.tab_pokemon_stats = QtWidgets.QWidget()
        self.tab_pokemon_stats.setObjectName("tab_pokemon_stats")
        self.tab_pokemon_stats_grid = QtWidgets.QGridLayout(self.tab_pokemon_stats)
        self.tab_pokemon_stats_grid.setObjectName("tab_pokemon_stats_grid")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(32)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_exp = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_exp.setObjectName("groupBox_exp")
        self.formLayout_exp = QtWidgets.QFormLayout(self.groupBox_exp)
        self.formLayout_exp.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_exp.setObjectName("formLayout_exp")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_exp)
        self.label_20.setObjectName("label_20")
        self.formLayout_exp.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_20
        )
        self.exp_growth_rate = QtWidgets.QComboBox(parent=self.groupBox_exp)
        self.exp_growth_rate.setObjectName("exp_growth_rate")
        self.formLayout_exp.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.exp_growth_rate
        )
        self.label_21 = QtWidgets.QLabel(parent=self.groupBox_exp)
        self.label_21.setObjectName("label_21")
        self.formLayout_exp.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_21
        )
        self.exp_yield = QtWidgets.QSpinBox(parent=self.groupBox_exp)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exp_yield.sizePolicy().hasHeightForWidth())
        self.exp_yield.setSizePolicy(sizePolicy)
        self.exp_yield.setMinimumSize(QtCore.QSize(120, 0))
        self.exp_yield.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_yield.setMinimum(10)
        self.exp_yield.setMaximum(1000)
        self.exp_yield.setObjectName("exp_yield")
        self.formLayout_exp.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.exp_yield
        )
        self.verticalLayout_3.addWidget(self.groupBox_exp)
        self.groupBox_gender = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_gender.setObjectName("groupBox_gender")
        self.formLayout_gender = QtWidgets.QFormLayout(self.groupBox_gender)
        self.formLayout_gender.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_gender.setObjectName("formLayout_gender")
        self.gender_ratio_label = QtWidgets.QLabel(parent=self.groupBox_gender)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gender_ratio_label.sizePolicy().hasHeightForWidth()
        )
        self.gender_ratio_label.setSizePolicy(sizePolicy)
        self.gender_ratio_label.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.gender_ratio_label.setFont(font)
        self.gender_ratio_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.gender_ratio_label.setObjectName("gender_ratio_label")
        self.formLayout_gender.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.gender_ratio_label
        )
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gender_ratio_minus1 = QtWidgets.QPushButton(parent=self.groupBox_gender)
        self.gender_ratio_minus1.setMaximumSize(QtCore.QSize(15, 16777215))
        self.gender_ratio_minus1.setObjectName("gender_ratio_minus1")
        self.horizontalLayout_8.addWidget(self.gender_ratio_minus1)
        self.gender_ratio = QtWidgets.QSlider(parent=self.groupBox_gender)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_ratio.sizePolicy().hasHeightForWidth())
        self.gender_ratio.setSizePolicy(sizePolicy)
        self.gender_ratio.setMinimumSize(QtCore.QSize(140, 0))
        self.gender_ratio.setMaximum(255)
        self.gender_ratio.setSingleStep(1)
        self.gender_ratio.setPageStep(16)
        self.gender_ratio.setProperty("value", 128)
        self.gender_ratio.setTracking(True)
        self.gender_ratio.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.gender_ratio.setInvertedAppearance(False)
        self.gender_ratio.setInvertedControls(False)
        self.gender_ratio.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.gender_ratio.setTickInterval(0)
        self.gender_ratio.setObjectName("gender_ratio")
        self.horizontalLayout_8.addWidget(self.gender_ratio)
        self.gender_ratio_plus1 = QtWidgets.QPushButton(parent=self.groupBox_gender)
        self.gender_ratio_plus1.setMaximumSize(QtCore.QSize(15, 16777215))
        self.gender_ratio_plus1.setObjectName("gender_ratio_plus1")
        self.horizontalLayout_8.addWidget(self.gender_ratio_plus1)
        self.formLayout_gender.setLayout(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_8
        )
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_gender)
        self.label_18.setObjectName("label_18")
        self.formLayout_gender.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_18
        )
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.egg_group_1 = QtWidgets.QComboBox(parent=self.groupBox_gender)
        self.egg_group_1.setObjectName("egg_group_1")
        self.horizontalLayout_4.addWidget(self.egg_group_1)
        self.egg_group_2 = QtWidgets.QComboBox(parent=self.groupBox_gender)
        self.egg_group_2.setObjectName("egg_group_2")
        self.horizontalLayout_4.addWidget(self.egg_group_2)
        self.formLayout_gender.setLayout(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_4
        )
        self.label_27 = QtWidgets.QLabel(parent=self.groupBox_gender)
        self.label_27.setObjectName("label_27")
        self.formLayout_gender.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_27
        )
        self.egg_cycles = QtWidgets.QSpinBox(parent=self.groupBox_gender)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.egg_cycles.sizePolicy().hasHeightForWidth())
        self.egg_cycles.setSizePolicy(sizePolicy)
        self.egg_cycles.setMinimumSize(QtCore.QSize(120, 0))
        self.egg_cycles.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.egg_cycles.setMinimum(5)
        self.egg_cycles.setMaximum(255)
        self.egg_cycles.setObjectName("egg_cycles")
        self.formLayout_gender.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.egg_cycles
        )
        self.verticalLayout_3.addWidget(self.groupBox_gender)
        self.tab_pokemon_stats_grid.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(32)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_types = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_types.setObjectName("groupBox_types")
        self.horizontalLayout_types = QtWidgets.QHBoxLayout(self.groupBox_types)
        self.horizontalLayout_types.setContentsMargins(-1, 12, -1, 12)
        self.horizontalLayout_types.setObjectName("horizontalLayout_types")
        self.type1 = QtWidgets.QComboBox(parent=self.groupBox_types)
        self.type1.setObjectName("type1")
        self.horizontalLayout_types.addWidget(self.type1)
        self.type2 = QtWidgets.QComboBox(parent=self.groupBox_types)
        self.type2.setObjectName("type2")
        self.horizontalLayout_types.addWidget(self.type2)
        self.verticalLayout_2.addWidget(self.groupBox_types)
        self.groupBox_abilities = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_abilities.setObjectName("groupBox_abilities")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_abilities)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_abilities)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_17
        )
        self.ability1 = QtWidgets.QComboBox(parent=self.groupBox_abilities)
        self.ability1.setEditable(True)
        self.ability1.setObjectName("ability1")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ability1
        )
        self.label_50 = QtWidgets.QLabel(parent=self.groupBox_abilities)
        self.label_50.setObjectName("label_50")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_50
        )
        self.ability2 = QtWidgets.QComboBox(parent=self.groupBox_abilities)
        self.ability2.setEditable(True)
        self.ability2.setObjectName("ability2")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ability2
        )
        # FireRed does not have Hidden Abilities; remove third ability control
        self.verticalLayout_2.addWidget(self.groupBox_abilities)
        self.tab_pokemon_stats_grid.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(32)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_heldItems = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_heldItems.setObjectName("groupBox_heldItems")
        self.formLayout_heldItems = QtWidgets.QFormLayout(self.groupBox_heldItems)
        self.formLayout_heldItems.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_heldItems.setObjectName("formLayout_heldItems")
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox_heldItems)
        self.label_23.setObjectName("label_23")
        self.formLayout_heldItems.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_23
        )
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox_heldItems)
        self.label_24.setObjectName("label_24")
        self.formLayout_heldItems.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_24
        )
        self.held_item_common = QtWidgets.QComboBox(parent=self.groupBox_heldItems)
        self.held_item_common.setEditable(True)
        self.held_item_common.setObjectName("held_item_common")
        self.formLayout_heldItems.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.held_item_common
        )
        self.held_item_rare = QtWidgets.QComboBox(parent=self.groupBox_heldItems)
        self.held_item_rare.setEditable(True)
        self.held_item_rare.setObjectName("held_item_rare")
        self.formLayout_heldItems.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.held_item_rare
        )
        self.verticalLayout_4.addWidget(self.groupBox_heldItems)
        self.groupBox_rates = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_rates.setObjectName("groupBox_rates")
        self.formLayout_rates = QtWidgets.QFormLayout(self.groupBox_rates)
        self.formLayout_rates.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_rates.setObjectName("formLayout_rates")
        self.label_25 = QtWidgets.QLabel(parent=self.groupBox_rates)
        self.label_25.setObjectName("label_25")
        self.formLayout_rates.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_25
        )
        self.label_26 = QtWidgets.QLabel(parent=self.groupBox_rates)
        self.label_26.setObjectName("label_26")
        self.formLayout_rates.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_26
        )
        self.catch_rate = QtWidgets.QSpinBox(parent=self.groupBox_rates)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catch_rate.sizePolicy().hasHeightForWidth())
        self.catch_rate.setSizePolicy(sizePolicy)
        self.catch_rate.setMinimumSize(QtCore.QSize(120, 0))
        self.catch_rate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.catch_rate.setMinimum(3)
        self.catch_rate.setMaximum(255)
        self.catch_rate.setObjectName("catch_rate")
        self.formLayout_rates.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.catch_rate
        )
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.base_friendship = QtWidgets.QSpinBox(parent=self.groupBox_rates)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.base_friendship.sizePolicy().hasHeightForWidth()
        )
        self.base_friendship.setSizePolicy(sizePolicy)
        self.base_friendship.setMinimumSize(QtCore.QSize(80, 0))
        self.base_friendship.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_friendship.setRange(0, 255)   # u8
        self.base_friendship.setObjectName("base_friendship")
        self.horizontalLayout_5.addWidget(self.base_friendship)
        # "Standard" checkbox removed — not used by the application.
        self.formLayout_rates.setLayout(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_5
        )
        self.label_28 = QtWidgets.QLabel(parent=self.groupBox_rates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_rates.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_28
        )
        self.safari_zone_flee_rate = QtWidgets.QSpinBox(parent=self.groupBox_rates)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.safari_zone_flee_rate.sizePolicy().hasHeightForWidth()
        )
        self.safari_zone_flee_rate.setSizePolicy(sizePolicy)
        self.safari_zone_flee_rate.setMinimumSize(QtCore.QSize(120, 0))
        self.safari_zone_flee_rate.setWrapping(False)
        self.safari_zone_flee_rate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.safari_zone_flee_rate.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows
        )
        self.safari_zone_flee_rate.setSpecialValueText("")
        self.safari_zone_flee_rate.setMaximum(255)
        self.safari_zone_flee_rate.setObjectName("safari_zone_flee_rate")
        self.formLayout_rates.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.safari_zone_flee_rate
        )
        self.verticalLayout_4.addWidget(self.groupBox_rates)
        self.tab_pokemon_stats_grid.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_baseStats = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_baseStats.setObjectName("groupBox_baseStats")
        self.formLayout_baseStats = QtWidgets.QFormLayout(self.groupBox_baseStats)
        self.formLayout_baseStats.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_baseStats.setObjectName("formLayout_baseStats")
        self.label = QtWidgets.QLabel(parent=self.groupBox_baseStats)
        self.label.setObjectName("label")
        self.formLayout_baseStats.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label
        )
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_baseStats)
        self.label_5.setObjectName("label_5")
        self.formLayout_baseStats.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5
        )
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_baseStats)
        self.label_7.setObjectName("label_7")
        self.formLayout_baseStats.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7
        )
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_baseStats)
        self.label_9.setObjectName("label_9")
        self.formLayout_baseStats.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9
        )
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_baseStats)
        self.label_10.setObjectName("label_10")
        self.formLayout_baseStats.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10
        )
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_baseStats)
        self.label_11.setObjectName("label_11")
        self.formLayout_baseStats.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11
        )
        self.base_hp = QtWidgets.QSpinBox(parent=self.groupBox_baseStats)
        self.base_hp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_hp.sizePolicy().hasHeightForWidth())
        self.base_hp.setSizePolicy(sizePolicy)
        self.base_hp.setMinimumSize(QtCore.QSize(60, 0))
        self.base_hp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.base_hp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_hp.setMinimum(1)
        self.base_hp.setMaximum(255)
        self.base_hp.setObjectName("base_hp")
        self.formLayout_baseStats.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.base_hp
        )
        self.base_atk = QtWidgets.QSpinBox(parent=self.groupBox_baseStats)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_atk.sizePolicy().hasHeightForWidth())
        self.base_atk.setSizePolicy(sizePolicy)
        self.base_atk.setMinimumSize(QtCore.QSize(60, 0))
        self.base_atk.setMaximumSize(QtCore.QSize(100, 16777215))
        self.base_atk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_atk.setMinimum(1)
        self.base_atk.setMaximum(255)
        self.base_atk.setObjectName("base_atk")
        self.formLayout_baseStats.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.base_atk
        )
        self.base_def = QtWidgets.QSpinBox(parent=self.groupBox_baseStats)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_def.sizePolicy().hasHeightForWidth())
        self.base_def.setSizePolicy(sizePolicy)
        self.base_def.setMinimumSize(QtCore.QSize(60, 0))
        self.base_def.setMaximumSize(QtCore.QSize(100, 16777215))
        self.base_def.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_def.setMinimum(1)
        self.base_def.setMaximum(255)
        self.base_def.setObjectName("base_def")
        self.formLayout_baseStats.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.base_def
        )
        self.base_spatk = QtWidgets.QSpinBox(parent=self.groupBox_baseStats)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_spatk.sizePolicy().hasHeightForWidth())
        self.base_spatk.setSizePolicy(sizePolicy)
        self.base_spatk.setMinimumSize(QtCore.QSize(60, 0))
        self.base_spatk.setMaximumSize(QtCore.QSize(100, 16777215))
        self.base_spatk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_spatk.setMinimum(1)
        self.base_spatk.setMaximum(255)
        self.base_spatk.setObjectName("base_spatk")
        self.formLayout_baseStats.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.base_spatk
        )
        self.base_spdef = QtWidgets.QSpinBox(parent=self.groupBox_baseStats)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_spdef.sizePolicy().hasHeightForWidth())
        self.base_spdef.setSizePolicy(sizePolicy)
        self.base_spdef.setMinimumSize(QtCore.QSize(60, 0))
        self.base_spdef.setMaximumSize(QtCore.QSize(100, 16777215))
        self.base_spdef.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_spdef.setMinimum(1)
        self.base_spdef.setMaximum(255)
        self.base_spdef.setObjectName("base_spdef")
        self.formLayout_baseStats.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.base_spdef
        )
        self.base_speed = QtWidgets.QSpinBox(parent=self.groupBox_baseStats)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_speed.sizePolicy().hasHeightForWidth())
        self.base_speed.setSizePolicy(sizePolicy)
        self.base_speed.setMinimumSize(QtCore.QSize(60, 0))
        self.base_speed.setMaximumSize(QtCore.QSize(100, 16777215))
        self.base_speed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_speed.setMinimum(1)
        self.base_speed.setMaximum(255)
        self.base_speed.setObjectName("base_speed")
        self.formLayout_baseStats.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.base_speed
        )
        self.horizontalLayout_2.addWidget(self.groupBox_baseStats)
        self.groupBox_evYield = QtWidgets.QGroupBox(parent=self.tab_pokemon_stats)
        self.groupBox_evYield.setObjectName("groupBox_evYield")
        self.formLayout_evYield = QtWidgets.QFormLayout(self.groupBox_evYield)
        self.formLayout_evYield.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_evYield.setObjectName("formLayout_evYield")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_evYield)
        self.label_4.setObjectName("label_4")
        self.formLayout_evYield.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4
        )
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_evYield)
        self.label_6.setObjectName("label_6")
        self.formLayout_evYield.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6
        )
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_evYield)
        self.label_8.setObjectName("label_8")
        self.formLayout_evYield.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8
        )
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_evYield)
        self.label_12.setObjectName("label_12")
        self.formLayout_evYield.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12
        )
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_evYield)
        self.label_13.setObjectName("label_13")
        self.formLayout_evYield.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13
        )
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_evYield)
        self.label_14.setObjectName("label_14")
        self.formLayout_evYield.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_14
        )
        self.evs_hp = QtWidgets.QSpinBox(parent=self.groupBox_evYield)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evs_hp.sizePolicy().hasHeightForWidth())
        self.evs_hp.setSizePolicy(sizePolicy)
        self.evs_hp.setMinimumSize(QtCore.QSize(60, 0))
        self.evs_hp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.evs_hp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evs_hp.setMaximum(3)
        self.evs_hp.setObjectName("evs_hp")
        self.formLayout_evYield.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.evs_hp
        )
        self.evs_atk = QtWidgets.QSpinBox(parent=self.groupBox_evYield)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evs_atk.sizePolicy().hasHeightForWidth())
        self.evs_atk.setSizePolicy(sizePolicy)
        self.evs_atk.setMinimumSize(QtCore.QSize(60, 0))
        self.evs_atk.setMaximumSize(QtCore.QSize(100, 16777215))
        self.evs_atk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evs_atk.setMaximum(3)
        self.evs_atk.setObjectName("evs_atk")
        self.formLayout_evYield.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.evs_atk
        )
        self.evs_def = QtWidgets.QSpinBox(parent=self.groupBox_evYield)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evs_def.sizePolicy().hasHeightForWidth())
        self.evs_def.setSizePolicy(sizePolicy)
        self.evs_def.setMinimumSize(QtCore.QSize(60, 0))
        self.evs_def.setMaximumSize(QtCore.QSize(100, 16777215))
        self.evs_def.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evs_def.setMaximum(3)
        self.evs_def.setObjectName("evs_def")
        self.formLayout_evYield.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.evs_def
        )
        self.evs_spatk = QtWidgets.QSpinBox(parent=self.groupBox_evYield)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evs_spatk.sizePolicy().hasHeightForWidth())
        self.evs_spatk.setSizePolicy(sizePolicy)
        self.evs_spatk.setMinimumSize(QtCore.QSize(60, 0))
        self.evs_spatk.setMaximumSize(QtCore.QSize(100, 16777215))
        self.evs_spatk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evs_spatk.setMaximum(3)
        self.evs_spatk.setObjectName("evs_spatk")
        self.formLayout_evYield.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.evs_spatk
        )
        self.evs_spdef = QtWidgets.QSpinBox(parent=self.groupBox_evYield)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evs_spdef.sizePolicy().hasHeightForWidth())
        self.evs_spdef.setSizePolicy(sizePolicy)
        self.evs_spdef.setMinimumSize(QtCore.QSize(60, 0))
        self.evs_spdef.setMaximumSize(QtCore.QSize(100, 16777215))
        self.evs_spdef.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evs_spdef.setMaximum(3)
        self.evs_spdef.setObjectName("evs_spdef")
        self.formLayout_evYield.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.evs_spdef
        )
        self.evs_speed = QtWidgets.QSpinBox(parent=self.groupBox_evYield)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evs_speed.sizePolicy().hasHeightForWidth())
        self.evs_speed.setSizePolicy(sizePolicy)
        self.evs_speed.setMinimumSize(QtCore.QSize(60, 0))
        self.evs_speed.setMaximumSize(QtCore.QSize(100, 16777215))
        self.evs_speed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evs_speed.setMaximum(3)
        self.evs_speed.setObjectName("evs_speed")
        self.formLayout_evYield.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.evs_speed
        )
        self.horizontalLayout_2.addWidget(self.groupBox_evYield)
        self.tab_pokemon_stats_grid.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tab_pokemon_data.addTab(self.tab_pokemon_stats, "")
        self.tab_pokemon_evos = QtWidgets.QWidget()
        self.tab_pokemon_evos.setObjectName("tab_pokemon_evos")
        self.tab_pokemon_evos_grid = QtWidgets.QGridLayout(self.tab_pokemon_evos)
        self.tab_pokemon_evos_grid.setObjectName("tab_pokemon_evos_grid")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_evos = QtWidgets.QGroupBox(parent=self.tab_pokemon_evos)
        self.groupBox_evos.setObjectName("groupBox_evos")
        self.verticalLayout_evos = QtWidgets.QVBoxLayout(self.groupBox_evos)
        self.verticalLayout_evos.setObjectName("verticalLayout_evos")
        self.evolutions = DeselectableTreeWidget(parent=self.groupBox_evos)
        self.evolutions.setAutoFillBackground(False)
        self.evolutions.setProperty("showDropIndicator", False)
        self.evolutions.setHeaderHidden(False)
        self.evolutions.setObjectName("evolutions")
        item_0 = QtWidgets.QTreeWidgetItem(self.evolutions)
        self.evolutions.header().setVisible(True)
        self.evolutions.header().setCascadingSectionResizes(True)
        self.evolutions.header().setDefaultSectionSize(100)
        self.evolutions.header().setHighlightSections(False)
        self.evolutions.header().setMinimumSectionSize(100)
        self.evolutions.header().setStretchLastSection(True)
        self.verticalLayout_evos.addWidget(self.evolutions)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.evo_species = QtWidgets.QComboBox(parent=self.groupBox_evos)
        self.evo_species.setEnabled(False)
        self.evo_species.setMinimumSize(QtCore.QSize(220, 0))
        self.evo_species.setEditable(True)
        self.evo_species.setObjectName("evo_species")
        self.evo_species.addItem("")
        self.horizontalLayout_7.addWidget(self.evo_species)
        self.evo_method = QtWidgets.QComboBox(parent=self.groupBox_evos)
        self.evo_method.setEnabled(False)
        self.evo_method.setObjectName("evo_method")
        self.evo_method.addItem("")
        self.horizontalLayout_7.addWidget(self.evo_method)
        self.evo_param = QtWidgets.QComboBox(parent=self.groupBox_evos)
        self.evo_param.setEnabled(False)
        self.evo_param.setEditable(False)
        self.evo_param.setObjectName("evo_param")
        self.evo_param.addItem("")
        self.horizontalLayout_7.addWidget(self.evo_param)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.groupBox_evos)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.verticalLayout_evos.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.evoDeleteButton = QtWidgets.QPushButton(parent=self.groupBox_evos)
        self.evoDeleteButton.setEnabled(False)
        self.evoDeleteButton.setFlat(False)
        self.evoDeleteButton.setObjectName("evoDeleteButton")
        self.horizontalLayout_11.addWidget(self.evoDeleteButton)
        self.verticalLayout_evos.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addWidget(self.groupBox_evos)
        self.tab_pokemon_evos_grid.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tab_pokemon_data.addTab(self.tab_pokemon_evos, "")
        self.tab_pokemon_moves = QtWidgets.QWidget()
        self.tab_pokemon_moves.setObjectName("tab_pokemon_moves")
        self.tab_pokemon_moves_grid = QtWidgets.QGridLayout(self.tab_pokemon_moves)
        self.tab_pokemon_moves_grid.setObjectName("tab_pokemon_moves_grid")
        self.moves_table = QtWidgets.QTableWidget(parent=self.tab_pokemon_moves)
        self.moves_table.setObjectName("moves_table")
        self.moves_table.setColumnCount(7)
        self.moves_table.setHorizontalHeaderLabels(
            [
                "Constant",
                "Name",
                "Power",
                "Accuracy",
                "PP",
                "Type",
                "Description",
            ]
        )
        self.moves_table.horizontalHeader().setStretchLastSection(True)
        self.tab_pokemon_moves_grid.addWidget(self.moves_table, 0, 0, 1, 1)
        self.tab_pokemon_data.addTab(self.tab_pokemon_moves, "")
        self.tab_pokemon_graphics = QtWidgets.QWidget()
        self.tab_pokemon_graphics.setObjectName("tab_pokemon_graphics")
        self.tab_pokemon_graphics_grid = QtWidgets.QGridLayout(
            self.tab_pokemon_graphics
        )
        self.tab_pokemon_graphics_grid.setObjectName("tab_pokemon_graphics_grid")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_33 = QtWidgets.QLabel(parent=self.tab_pokemon_graphics)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_33
        )
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frontPic_0 = QtWidgets.QPushButton(parent=self.tab_pokemon_graphics)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frontPic_0.sizePolicy().hasHeightForWidth())
        self.frontPic_0.setSizePolicy(sizePolicy)
        self.frontPic_0.setMinimumSize(QtCore.QSize(70, 70))
        self.frontPic_0.setMaximumSize(QtCore.QSize(70, 70))
        self.frontPic_0.setText("")
        self.frontPic_0.setCheckable(False)
        self.frontPic_0.setObjectName("frontPic_0")
        self.horizontalLayout_9.addWidget(self.frontPic_0)
        self.frontPic_1 = QtWidgets.QPushButton(parent=self.tab_pokemon_graphics)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frontPic_1.sizePolicy().hasHeightForWidth())
        self.frontPic_1.setSizePolicy(sizePolicy)
        self.frontPic_1.setMinimumSize(QtCore.QSize(70, 70))
        self.frontPic_1.setMaximumSize(QtCore.QSize(70, 70))
        self.frontPic_1.setText("")
        self.frontPic_1.setCheckable(False)
        self.frontPic_1.setObjectName("frontPic_1")
        self.horizontalLayout_9.addWidget(self.frontPic_1)
        self.formLayout_2.setLayout(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_9
        )
        self.label_34 = QtWidgets.QLabel(parent=self.tab_pokemon_graphics)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_34
        )
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.backPic = QtWidgets.QPushButton(parent=self.tab_pokemon_graphics)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backPic.sizePolicy().hasHeightForWidth())
        self.backPic.setSizePolicy(sizePolicy)
        self.backPic.setMinimumSize(QtCore.QSize(70, 70))
        self.backPic.setMaximumSize(QtCore.QSize(70, 70))
        self.backPic.setText("")
        self.backPic.setCheckable(False)
        self.backPic.setObjectName("backPic")
        self.horizontalLayout_10.addWidget(self.backPic)
        self.formLayout_2.setLayout(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_10
        )
        self.label_51 = QtWidgets.QLabel(parent=self.tab_pokemon_graphics)
        self.label_51.setObjectName("label_51")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_51
        )
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.iconPic = QtWidgets.QPushButton(parent=self.tab_pokemon_graphics)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconPic.sizePolicy().hasHeightForWidth())
        self.iconPic.setSizePolicy(sizePolicy)
        self.iconPic.setMinimumSize(QtCore.QSize(64, 64))
        self.iconPic.setMaximumSize(QtCore.QSize(64, 64))
        self.iconPic.setText("")
        self.iconPic.setCheckable(False)
        self.iconPic.setObjectName("iconPic")
        self.horizontalLayout_11.addWidget(self.iconPic)
        self.formLayout_2.setLayout(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_11
        )
        self.label_52 = QtWidgets.QLabel(parent=self.tab_pokemon_graphics)
        self.label_52.setObjectName("label_52")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_52
        )
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.footprintPic = QtWidgets.QPushButton(parent=self.tab_pokemon_graphics)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footprintPic.sizePolicy().hasHeightForWidth())
        self.footprintPic.setSizePolicy(sizePolicy)
        self.footprintPic.setMinimumSize(QtCore.QSize(56, 28))
        self.footprintPic.setMaximumSize(QtCore.QSize(56, 28))
        self.footprintPic.setText("")
        self.footprintPic.setCheckable(False)
        self.footprintPic.setObjectName("footprintPic")
        self.horizontalLayout_12.addWidget(self.footprintPic)
        self.formLayout_2.setLayout(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_12
        )
        self.tab_pokemon_graphics_grid.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.tab_pokemon_data.addTab(self.tab_pokemon_graphics, "")
        self.tree_pokemon = QtWidgets.QTreeWidget(parent=self.tab_pokemon)
        self.tree_pokemon.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.tree_pokemon.setFont(font)
        self.tree_pokemon.setObjectName("tree_pokemon")
        self.pokemon_list_splitter = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal, parent=self.tab_pokemon)
        self.pokemon_list_splitter.setObjectName("pokemon_list_splitter")
        self.pokemon_list_splitter.addWidget(self.tree_pokemon)
        self.pokemon_list_splitter.addWidget(self.tab_pokemon_data)
        self.pokemon_list_splitter.setStretchFactor(0, 0)
        self.pokemon_list_splitter.setStretchFactor(1, 1)
        self.tab_pokemon_grid.addWidget(self.pokemon_list_splitter, 0, 0, 1, 1)
        self.mainTabs.addTab(self.tab_pokemon, "")
        self.tab_pokedex = QtWidgets.QWidget()
        self.tab_pokedex.setObjectName("tab_pokedex")
        self.tab_pokedex_grid = QtWidgets.QGridLayout(self.tab_pokedex)
        self.tab_pokedex_grid.setObjectName("tab_pokedex_grid")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_pokedex)
        self.label_3.setObjectName("label_3")
        self.tab_pokedex_grid.addWidget(self.label_3, 0, 1, 1, 1)
        self.list_pokedex_national = QtWidgets.QListWidget(parent=self.tab_pokedex)
        self.list_pokedex_national.setUniformItemSizes(False)
        self.list_pokedex_national.setDragEnabled(True)
        self.list_pokedex_national.setDragDropMode(
            QtWidgets.QAbstractItemView.DragDropMode.InternalMove
        )
        self.list_pokedex_national.setDefaultDropAction(QtCore.Qt.DropAction.CopyAction)
        self.list_pokedex_national.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.list_pokedex_national.setObjectName("list_pokedex_national")
        self.tab_pokedex_grid.addWidget(self.list_pokedex_national, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.tab_pokedex)
        self.label_2.setObjectName("label_2")
        self.tab_pokedex_grid.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_pokedex_regional = QtWidgets.QListWidget(parent=self.tab_pokedex)
        self.list_pokedex_regional.setDragEnabled(True)
        self.list_pokedex_regional.setDragDropMode(
            QtWidgets.QAbstractItemView.DragDropMode.InternalMove
        )
        self.list_pokedex_regional.setDefaultDropAction(QtCore.Qt.DropAction.CopyAction)
        self.list_pokedex_regional.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.list_pokedex_regional.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.list_pokedex_regional.setObjectName("list_pokedex_regional")
        self.verticalLayout.addWidget(self.list_pokedex_regional)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.tab_pokedex)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab_pokedex)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.tab_pokedex_grid.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.mainTabs.addTab(self.tab_pokedex, "")
        self.tab_items = QtWidgets.QWidget()
        self.tab_items.setObjectName("tab_items")
        self.tab_items_grid = QtWidgets.QGridLayout(self.tab_items)
        self.tab_items_grid.setObjectName("tab_items_grid")
        self.items_table = QtWidgets.QTableWidget(parent=self.tab_items)
        self.items_table.setObjectName("items_table")
        self.items_table.setColumnCount(4)
        self.items_table.setHorizontalHeaderLabels(
            [
                "Constant",
                "Name",
                "Price",
                "Effect",
            ]
        )
        self.items_table.horizontalHeader().setStretchLastSection(True)
        self.tab_items_grid.addWidget(self.items_table, 0, 0, 1, 1)
        self.mainTabs.addTab(self.tab_items, "")
        self.tab_starters = QtWidgets.QWidget()
        self.tab_starters.setObjectName("tab_starters")
        self.tab_starters_grid = QtWidgets.QGridLayout(self.tab_starters)
        self.tab_starters_grid.setObjectName("tab_starters_grid")
        self.groupBox_starter3 = QtWidgets.QGroupBox(parent=self.tab_starters)
        self.groupBox_starter3.setObjectName("groupBox_starter3")
        self.groupBox_starter3_form = QtWidgets.QFormLayout(self.groupBox_starter3)
        self.groupBox_starter3_form.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow
        )
        self.groupBox_starter3_form.setRowWrapPolicy(
            QtWidgets.QFormLayout.RowWrapPolicy.DontWrapRows
        )
        self.groupBox_starter3_form.setVerticalSpacing(12)
        self.groupBox_starter3_form.setObjectName("groupBox_starter3_form")
        self.label_37 = QtWidgets.QLabel(parent=self.groupBox_starter3)
        self.label_37.setObjectName("label_37")
        self.groupBox_starter3_form.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_37
        )
        self.starter3_species = QtWidgets.QComboBox(parent=self.groupBox_starter3)
        self.starter3_species.setEditable(True)
        self.starter3_species.setObjectName("starter3_species")
        self.groupBox_starter3_form.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter3_species
        )
        self.label_40 = QtWidgets.QLabel(parent=self.groupBox_starter3)
        self.label_40.setObjectName("label_40")
        self.groupBox_starter3_form.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_40
        )
        self.starter3_level = QtWidgets.QSpinBox(parent=self.groupBox_starter3)
        self.starter3_level.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.starter3_level.setMinimum(1)
        self.starter3_level.setMaximum(100)
        self.starter3_level.setProperty("value", 5)
        self.starter3_level.setObjectName("starter3_level")
        self.groupBox_starter3_form.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter3_level
        )
        self.label_43 = QtWidgets.QLabel(parent=self.groupBox_starter3)
        self.label_43.setObjectName("label_43")
        self.groupBox_starter3_form.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_43
        )
        self.starter3_item = QtWidgets.QComboBox(parent=self.groupBox_starter3)
        self.starter3_item.setEditable(True)
        self.starter3_item.setObjectName("starter3_item")
        self.groupBox_starter3_form.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter3_item
        )
        self.label_46 = QtWidgets.QLabel(parent=self.groupBox_starter3)
        self.label_46.setObjectName("label_46")
        self.groupBox_starter3_form.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_46
        )
        self.starter3_move = QtWidgets.QComboBox(parent=self.groupBox_starter3)
        self.starter3_move.setObjectName("starter3_move")
        self.groupBox_starter3_form.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter3_move
        )
        self.label_49 = QtWidgets.QLabel(parent=self.groupBox_starter3)
        self.label_49.setObjectName("label_49")
        self.groupBox_starter3_form.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_49
        )
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.starter3_ability_num = QtWidgets.QComboBox(parent=self.groupBox_starter3)
        self.starter3_ability_num.setEnabled(False)
        self.starter3_ability_num.setObjectName("starter3_ability_num")
        self.horizontalLayout_12.addWidget(self.starter3_ability_num)
        self.starter3_ability_custom = QtWidgets.QCheckBox(
            parent=self.groupBox_starter3
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.starter3_ability_custom.setFont(font)
        self.starter3_ability_custom.setObjectName("starter3_ability_custom")
        self.horizontalLayout_12.addWidget(self.starter3_ability_custom)
        self.groupBox_starter3_form.setLayout(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_12
        )
        self.tab_starters_grid.addWidget(self.groupBox_starter3, 0, 2, 1, 1)
        self.groupBox_starter2 = QtWidgets.QGroupBox(parent=self.tab_starters)
        self.groupBox_starter2.setObjectName("groupBox_starter2")
        self.groupBox_starter2_form = QtWidgets.QFormLayout(self.groupBox_starter2)
        self.groupBox_starter2_form.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow
        )
        self.groupBox_starter2_form.setRowWrapPolicy(
            QtWidgets.QFormLayout.RowWrapPolicy.DontWrapRows
        )
        self.groupBox_starter2_form.setVerticalSpacing(12)
        self.groupBox_starter2_form.setObjectName("groupBox_starter2_form")
        self.label_36 = QtWidgets.QLabel(parent=self.groupBox_starter2)
        self.label_36.setObjectName("label_36")
        self.groupBox_starter2_form.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_36
        )
        self.starter2_species = QtWidgets.QComboBox(parent=self.groupBox_starter2)
        self.starter2_species.setEditable(True)
        self.starter2_species.setObjectName("starter2_species")
        self.groupBox_starter2_form.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter2_species
        )
        self.label_39 = QtWidgets.QLabel(parent=self.groupBox_starter2)
        self.label_39.setObjectName("label_39")
        self.groupBox_starter2_form.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_39
        )
        self.starter2_level = QtWidgets.QSpinBox(parent=self.groupBox_starter2)
        self.starter2_level.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.starter2_level.setMinimum(1)
        self.starter2_level.setMaximum(100)
        self.starter2_level.setProperty("value", 5)
        self.starter2_level.setObjectName("starter2_level")
        self.groupBox_starter2_form.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter2_level
        )
        self.label_42 = QtWidgets.QLabel(parent=self.groupBox_starter2)
        self.label_42.setObjectName("label_42")
        self.groupBox_starter2_form.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_42
        )
        self.starter2_item = QtWidgets.QComboBox(parent=self.groupBox_starter2)
        self.starter2_item.setEditable(True)
        self.starter2_item.setObjectName("starter2_item")
        self.groupBox_starter2_form.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter2_item
        )
        self.label_45 = QtWidgets.QLabel(parent=self.groupBox_starter2)
        self.label_45.setObjectName("label_45")
        self.groupBox_starter2_form.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_45
        )
        self.starter2_move = QtWidgets.QComboBox(parent=self.groupBox_starter2)
        self.starter2_move.setObjectName("starter2_move")
        self.groupBox_starter2_form.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter2_move
        )
        self.label_48 = QtWidgets.QLabel(parent=self.groupBox_starter2)
        self.label_48.setObjectName("label_48")
        self.groupBox_starter2_form.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_48
        )
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.starter2_ability_num = QtWidgets.QComboBox(parent=self.groupBox_starter2)
        self.starter2_ability_num.setEnabled(False)
        self.starter2_ability_num.setObjectName("starter2_ability_num")
        self.horizontalLayout_13.addWidget(self.starter2_ability_num)
        self.starter2_ability_custom = QtWidgets.QCheckBox(
            parent=self.groupBox_starter2
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.starter2_ability_custom.setFont(font)
        self.starter2_ability_custom.setObjectName("starter2_ability_custom")
        self.horizontalLayout_13.addWidget(self.starter2_ability_custom)
        self.groupBox_starter2_form.setLayout(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_13
        )
        self.tab_starters_grid.addWidget(self.groupBox_starter2, 0, 1, 1, 1)
        self.groupBox_starter1 = QtWidgets.QGroupBox(parent=self.tab_starters)
        self.groupBox_starter1.setObjectName("groupBox_starter1")
        self.groupBox_starter1_form = QtWidgets.QFormLayout(self.groupBox_starter1)
        self.groupBox_starter1_form.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow
        )
        self.groupBox_starter1_form.setRowWrapPolicy(
            QtWidgets.QFormLayout.RowWrapPolicy.DontWrapRows
        )
        self.groupBox_starter1_form.setVerticalSpacing(12)
        self.groupBox_starter1_form.setObjectName("groupBox_starter1_form")
        self.label_35 = QtWidgets.QLabel(parent=self.groupBox_starter1)
        self.label_35.setObjectName("label_35")
        self.groupBox_starter1_form.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_35
        )
        self.starter1_species = QtWidgets.QComboBox(parent=self.groupBox_starter1)
        self.starter1_species.setEditable(True)
        self.starter1_species.setObjectName("starter1_species")
        self.groupBox_starter1_form.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter1_species
        )
        self.label_38 = QtWidgets.QLabel(parent=self.groupBox_starter1)
        self.label_38.setObjectName("label_38")
        self.groupBox_starter1_form.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_38
        )
        self.starter1_level = QtWidgets.QSpinBox(parent=self.groupBox_starter1)
        self.starter1_level.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.starter1_level.setMinimum(1)
        self.starter1_level.setMaximum(100)
        self.starter1_level.setProperty("value", 5)
        self.starter1_level.setObjectName("starter1_level")
        self.groupBox_starter1_form.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter1_level
        )
        self.label_41 = QtWidgets.QLabel(parent=self.groupBox_starter1)
        self.label_41.setObjectName("label_41")
        self.groupBox_starter1_form.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_41
        )
        self.starter1_item = QtWidgets.QComboBox(parent=self.groupBox_starter1)
        self.starter1_item.setEditable(True)
        self.starter1_item.setObjectName("starter1_item")
        self.groupBox_starter1_form.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter1_item
        )
        self.label_44 = QtWidgets.QLabel(parent=self.groupBox_starter1)
        self.label_44.setObjectName("label_44")
        self.groupBox_starter1_form.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_44
        )
        self.starter1_move = QtWidgets.QComboBox(parent=self.groupBox_starter1)
        self.starter1_move.setObjectName("starter1_move")
        self.groupBox_starter1_form.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.starter1_move
        )
        self.label_47 = QtWidgets.QLabel(parent=self.groupBox_starter1)
        self.label_47.setObjectName("label_47")
        self.groupBox_starter1_form.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_47
        )
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.starter1_ability_num = QtWidgets.QComboBox(parent=self.groupBox_starter1)
        self.starter1_ability_num.setEnabled(False)
        self.starter1_ability_num.setObjectName("starter1_ability_num")
        self.horizontalLayout_14.addWidget(self.starter1_ability_num)
        self.starter1_ability_custom = QtWidgets.QCheckBox(
            parent=self.groupBox_starter1
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.starter1_ability_custom.setFont(font)
        self.starter1_ability_custom.setObjectName("starter1_ability_custom")
        self.horizontalLayout_14.addWidget(self.starter1_ability_custom)
        self.groupBox_starter1_form.setLayout(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_14
        )
        self.tab_starters_grid.addWidget(self.groupBox_starter1, 0, 0, 1, 1)
        # Equal column widths and push content to top
        self.tab_starters_grid.setColumnStretch(0, 1)
        self.tab_starters_grid.setColumnStretch(1, 1)
        self.tab_starters_grid.setColumnStretch(2, 1)
        self.tab_starters_grid.setRowStretch(1, 1)
        self.mainTabs.addTab(self.tab_starters, "")
        self.tab_trainers = QtWidgets.QWidget()
        self.tab_trainers.setObjectName("tab_trainers")
        self.tab_trainers_grid = QtWidgets.QGridLayout(self.tab_trainers)
        self.tab_trainers_grid.setObjectName("tab_trainers_grid")
        self.trainers_table = QtWidgets.QTableWidget(parent=self.tab_trainers)
        self.trainers_table.setObjectName("trainers_table")
        self.trainers_table.setColumnCount(7)
        self.trainers_table.setHorizontalHeaderLabels([
            "Constant",
            "Class",
            "Name",
            "Items",
            "Double",
            "AI Flags",
            "Party",
        ])
        self.trainers_table.horizontalHeader().setStretchLastSection(True)
        self.tab_trainers_grid.addWidget(self.trainers_table, 0, 0, 1, 1)
        self.mainTabs.addTab(self.tab_trainers, "")
        self.tab_ui = QtWidgets.QWidget()
        self.tab_ui.setObjectName("tab_ui")
        self.tab_ui_grid = QtWidgets.QGridLayout(self.tab_ui)
        self.tab_ui_grid.setObjectName("tab_ui_grid")
        self.mainTabs.addTab(self.tab_ui, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.tab_config_grid = QtWidgets.QGridLayout(self.tab_config)
        self.tab_config_grid.setObjectName("tab_config_grid")
        self.mainTabs.addTab(self.tab_config, "")
        self.verticalLayout_7.addWidget(self.mainTabs)
        self.layoutWidget = QtWidgets.QWidget(parent=self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.logOutput = QtWidgets.QTextBrowser(parent=self.groupBox)
        self.logOutput.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.logOutput.setObjectName("logOutput")
        self.horizontalLayout_16.addWidget(self.logOutput)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_6.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecent_Projects = QtWidgets.QMenu(parent=self.menuFile)
        self.menuRecent_Projects.setObjectName("menuRecent_Projects")
        self.menuProject = QtWidgets.QMenu(parent=self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(parent=MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionNew_Project = QtGui.QAction(parent=MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionClear = QtGui.QAction(parent=MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport_to_Patch_bps = QtGui.QAction(parent=MainWindow)
        self.actionExport_to_Patch_bps.setObjectName("actionExport_to_Patch_bps")
        self.actionChange_Plugin = QtGui.QAction(parent=MainWindow)
        self.actionChange_Plugin.setObjectName("actionChange_Plugin")
        self.actionOpen_in_Terminal = QtGui.QAction(parent=MainWindow)
        self.actionOpen_in_Terminal.setObjectName("actionOpen_in_Terminal")
        self.actionRename_Entity = QtGui.QAction(parent=MainWindow)
        self.actionRename_Entity.setObjectName("actionRename_Entity")
        self.actionRebuild_Caches = QtGui.QAction(parent=MainWindow)
        self.actionRebuild_Caches.setObjectName("actionRebuild_Caches")
        self.actionClear_Caches = QtGui.QAction(parent=MainWindow)
        self.actionClear_Caches.setObjectName("actionClear_Caches")
        self.actionOpen_Crashlogs_Folder = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Crashlogs_Folder.setObjectName("actionOpen_Crashlogs_Folder")
        self.actionOpen_Plugins_Folder = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Plugins_Folder.setMenuRole(
            QtGui.QAction.MenuRole.ApplicationSpecificRole
        )
        self.actionOpen_Plugins_Folder.setObjectName("actionOpen_Plugins_Folder")
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.menuRecent_Projects.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Plugins_Folder)
        self.menuProject.addAction(self.actionExport_to_Patch_bps)
        self.menuProject.addAction(self.actionChange_Plugin)
        self.menuTools.addAction(self.actionOpen_in_Terminal)
        self.menuTools.addAction(self.actionRename_Entity)
        self.menuTools.addAction(self.actionOpen_Crashlogs_Folder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabs.setCurrentIndex(0)
        self.tab_pokemon_data.setCurrentIndex(0)
        self.actionSave.triggered.connect(MainWindow.update_save)  # type: ignore
        self.actionOpen_in_Terminal.triggered.connect(MainWindow.update_action)  # type: ignore
        self.actionRename_Entity.triggered.connect(MainWindow.rename_entity)  # type: ignore
        self.actionNew_Project.triggered.connect(MainWindow.update_action)  # type: ignore
        self.actionChange_Plugin.triggered.connect(MainWindow.change_plugin)  # type: ignore
        self.actionOpen_Crashlogs_Folder.triggered.connect(MainWindow._open_crashlogs_folder)  # type: ignore
        self.gender_ratio.valueChanged["int"].connect(MainWindow.update)  # type: ignore
        self.gender_ratio_plus1.pressed.connect(MainWindow.update_gender_ratio_plus1)  # type: ignore
        self.tree_pokemon.itemSelectionChanged.connect(MainWindow.update_tree_pokemon)  # type: ignore
        self.gender_ratio_minus1.pressed.connect(MainWindow.update_gender_ratio_minus1)  # type: ignore
        self.mainTabs.currentChanged["int"].connect(MainWindow.update_main_tabs)  # type: ignore
        self.evolutions.itemSelectionChanged.connect(MainWindow.update)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PorySuite-Z"))
        self.label_32.setText(_translate("MainWindow", "Flags"))
        __sortingEnabled = self.species_flags.isSortingEnabled()
        self.species_flags.setSortingEnabled(False)
        item = self.species_flags.item(0)
        item.setText(_translate("MainWindow", "Legendary"))
        item = self.species_flags.item(1)
        item.setText(_translate("MainWindow", "Mythical"))
        item = self.species_flags.item(2)
        item.setText(_translate("MainWindow", "Ultra Beast"))
        item = self.species_flags.item(3)
        item.setText(_translate("MainWindow", "Mega Evolution"))
        item = self.species_flags.item(4)
        item.setText(_translate("MainWindow", "Alolan Form"))
        item = self.species_flags.item(5)
        item.setText(_translate("MainWindow", "Galarian Form"))
        item = self.species_flags.item(6)
        item.setText(_translate("MainWindow", "Hisuian Form"))
        item = self.species_flags.item(7)
        item.setText(_translate("MainWindow", "Paldean Form"))
        self.species_flags.setSortingEnabled(__sortingEnabled)
        self.label_22.setText(_translate("MainWindow", "Name"))
        self.label_29.setText(_translate("MainWindow", "Dex #"))
        self.dex_num.setText(_translate("MainWindow", "# 000"))
        self.label_30.setText(_translate("MainWindow", "Category"))
        self.label_31.setText(_translate("MainWindow", "Description"))
        self.species_description.setPlainText(
            _translate(
                "MainWindow",
                "Bulbasaur can be seen napping in bright\n"
                "sunlight. There is a seed on its back.\n"
                "By soaking up the sun's rays, the seed\n"
                "grows progressively larger.",
            )
        )
        self.tab_pokemon_data.setTabText(
            self.tab_pokemon_data.indexOf(self.tab_pokemon_info),
            _translate("MainWindow", "Info"),
        )
        self.groupBox_exp.setTitle(_translate("MainWindow", "Experience"))
        self.label_20.setText(_translate("MainWindow", "Growth Rate"))
        self.label_21.setText(_translate("MainWindow", "Exp Yield"))
        self.groupBox_gender.setTitle(_translate("MainWindow", "Gender/Breeding"))
        self.gender_ratio_label.setText(_translate("MainWindow", "50% Female"))
        self.gender_ratio_minus1.setText(_translate("MainWindow", "<"))
        self.gender_ratio_plus1.setText(_translate("MainWindow", ">"))
        self.label_18.setText(_translate("MainWindow", "Egg Groups"))
        self.label_27.setText(_translate("MainWindow", "Egg Cycles"))
        self.egg_cycles.setSuffix(_translate("MainWindow", " / 255"))
        self.groupBox_types.setTitle(_translate("MainWindow", "Types"))
        self.type1.setPlaceholderText(_translate("MainWindow", "Type 1"))
        self.type2.setPlaceholderText(_translate("MainWindow", "Type 2"))
        self.groupBox_abilities.setTitle(_translate("MainWindow", "Abilities"))
        self.label_17.setText(_translate("MainWindow", "1"))
        self.label_50.setText(_translate("MainWindow", "2"))
        # FireRed: no Hidden Ability label
        self.groupBox_heldItems.setTitle(_translate("MainWindow", "Held Items"))
        self.label_23.setText(_translate("MainWindow", "Common"))
        self.label_24.setText(_translate("MainWindow", "Rare"))
        self.groupBox_rates.setTitle(_translate("MainWindow", "Rates"))
        self.label_25.setText(_translate("MainWindow", "Catch Rate"))
        self.label_26.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p>The value to which a Pokémon\'s <span style=" font-weight:700;">Friendship</span> is set when caught or received from an event, NPC, or trade.</p><p>Most Pokémon have a standard <span style=" font-weight:700;">Base Friendship</span> of 70. This was lowered in Gen 8 to 50.</p></body></html>',
            )
        )
        self.label_26.setText(_translate("MainWindow", "Base Friendship"))
        self.catch_rate.setSuffix(_translate("MainWindow", " / 255"))
        # Standard checkbox removed
        self.label_28.setText(_translate("MainWindow", "Safari Zone Flee Rate"))
        self.safari_zone_flee_rate.setSuffix(_translate("MainWindow", " / 255"))
        self.groupBox_baseStats.setTitle(_translate("MainWindow", "Base Stats"))
        self.label.setText(_translate("MainWindow", "HP"))
        self.label_5.setText(_translate("MainWindow", "ATK"))
        self.label_7.setText(_translate("MainWindow", "DEF"))
        self.label_9.setText(_translate("MainWindow", "SP.ATK"))
        self.label_10.setText(_translate("MainWindow", "SP.DEF"))
        self.label_11.setText(_translate("MainWindow", "SPEED"))
        self.groupBox_evYield.setTitle(_translate("MainWindow", "EV Yield"))
        self.label_4.setText(_translate("MainWindow", "HP"))
        self.label_6.setText(_translate("MainWindow", "ATK"))
        self.label_8.setText(_translate("MainWindow", "DEF"))
        self.label_12.setText(_translate("MainWindow", "SP.ATK"))
        self.label_13.setText(_translate("MainWindow", "SP.DEF"))
        self.label_14.setText(_translate("MainWindow", "SPEED"))
        self.tab_pokemon_data.setTabText(
            self.tab_pokemon_data.indexOf(self.tab_pokemon_stats),
            _translate("MainWindow", "Stats"),
        )
        self.groupBox_evos.setTitle(_translate("MainWindow", "Evolutions"))
        self.evolutions.headerItem().setText(0, _translate("MainWindow", "Species"))
        self.evolutions.headerItem().setText(1, _translate("MainWindow", "Method"))
        self.evolutions.headerItem().setText(2, _translate("MainWindow", "Param"))
        __sortingEnabled = self.evolutions.isSortingEnabled()
        self.evolutions.setSortingEnabled(False)
        self.evolutions.topLevelItem(0).setText(
            0, _translate("MainWindow", "Add New Evolution...")
        )
        self.evolutions.setSortingEnabled(__sortingEnabled)
        self.evo_species.setItemText(0, _translate("MainWindow", "--Species--"))
        self.evo_method.setItemText(0, _translate("MainWindow", "--Method--"))
        self.evo_param.setItemText(0, _translate("MainWindow", "--Param--"))
        self.pushButton_7.setText(_translate("MainWindow", "Add"))
        self.evoDeleteButton.setText(
            _translate("MainWindow", "Delete Selected Evolution")
        )
        self.tab_pokemon_data.setTabText(
            self.tab_pokemon_data.indexOf(self.tab_pokemon_evos),
            _translate("MainWindow", "Evolutions"),
        )
        self.tab_pokemon_data.setTabText(
            self.tab_pokemon_data.indexOf(self.tab_pokemon_moves),
            _translate("MainWindow", "Moves"),
        )
        self.moves_table.setHorizontalHeaderLabels(
            [
                _translate("MainWindow", "Constant"),
                _translate("MainWindow", "Name"),
                _translate("MainWindow", "Power"),
                _translate("MainWindow", "Accuracy"),
                _translate("MainWindow", "PP"),
                _translate("MainWindow", "Type"),
                _translate("MainWindow", "Description"),
            ]
        )
        self.label_33.setText(_translate("MainWindow", "Front"))
        self.label_34.setText(_translate("MainWindow", "Back"))
        self.label_51.setText(_translate("MainWindow", "Icon"))
        self.label_52.setText(_translate("MainWindow", "Footprint"))
        self.tab_pokemon_data.setTabText(
            self.tab_pokemon_data.indexOf(self.tab_pokemon_graphics),
            _translate("MainWindow", "Graphics"),
        )
        self.tree_pokemon.headerItem().setText(0, _translate("MainWindow", "Species"))
        self.mainTabs.setTabText(
            self.mainTabs.indexOf(self.tab_pokemon), _translate("MainWindow", "Pokémon")
        )
        self.label_3.setText(_translate("MainWindow", "Regional Dex"))
        self.label_2.setText(_translate("MainWindow", "National Dex"))
        self.pushButton_4.setText(_translate("MainWindow", "Add"))
        self.pushButton_5.setText(_translate("MainWindow", "Remove"))
        self.mainTabs.setTabText(
            self.mainTabs.indexOf(self.tab_pokedex), _translate("MainWindow", "Pokédex")
        )
        self.items_table.setHorizontalHeaderLabels(
            [
                _translate("MainWindow", "Constant"),
                _translate("MainWindow", "Name"),
                _translate("MainWindow", "Price"),
                _translate("MainWindow", "Effect"),
            ]
        )
        self.mainTabs.setTabText(
            self.mainTabs.indexOf(self.tab_items), _translate("MainWindow", "Items")
        )
        self.groupBox_starter3.setTitle(_translate("MainWindow", "Starter 3"))
        self.label_37.setText(_translate("MainWindow", "Species"))
        self.label_40.setText(_translate("MainWindow", "Level"))
        self.label_43.setText(_translate("MainWindow", "Held Item"))
        self.label_46.setText(_translate("MainWindow", "Custom Move"))
        self.label_49.setText(_translate("MainWindow", "Ability"))
        self.starter3_ability_custom.setText(_translate("MainWindow", "Custom"))
        self.groupBox_starter2.setTitle(_translate("MainWindow", "Starter 2"))
        self.label_36.setText(_translate("MainWindow", "Species"))
        self.label_39.setText(_translate("MainWindow", "Level"))
        self.label_42.setText(_translate("MainWindow", "Held Item"))
        self.label_45.setText(_translate("MainWindow", "Custom Move"))
        self.label_48.setText(_translate("MainWindow", "Ability"))
        self.starter2_ability_custom.setText(_translate("MainWindow", "Custom"))
        self.groupBox_starter1.setTitle(_translate("MainWindow", "Starter 1"))
        self.label_35.setText(_translate("MainWindow", "Species"))
        self.label_38.setText(_translate("MainWindow", "Level"))
        self.label_41.setText(_translate("MainWindow", "Held Item"))
        self.label_44.setText(_translate("MainWindow", "Custom Move"))
        self.label_47.setText(_translate("MainWindow", "Ability"))
        self.starter1_ability_custom.setText(_translate("MainWindow", "Custom"))
        self.mainTabs.setTabText(
            self.mainTabs.indexOf(self.tab_starters),
            _translate("MainWindow", "Starters"),
        )
        self.mainTabs.setTabText(
            self.mainTabs.indexOf(self.tab_trainers),
            _translate("MainWindow", "Trainers"),
        )
        self.mainTabs.setTabText(
            self.mainTabs.indexOf(self.tab_ui), _translate("MainWindow", "UI")
        )
        self.mainTabs.setTabText(
            self.mainTabs.indexOf(self.tab_config), _translate("MainWindow", "Config")
        )
        self.groupBox.setTitle(_translate("MainWindow", "Output"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuRecent_Projects.setTitle(_translate("MainWindow", "Recent Projects"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen_Crashlogs_Folder.setText(_translate("MainWindow", "Open Crashlogs Folder"))
        self.action_Open.setText(_translate("MainWindow", "&Open Project..."))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionNew_Project.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExport_to_Patch_bps.setText(
            _translate("MainWindow", "Export to Patch file (.bps)")
        )
        self.actionExport_to_Patch_bps.setShortcut(
            _translate("MainWindow", "Ctrl+Shift+E")
        )
        self.actionOpen_in_Terminal.setText(_translate("MainWindow", "Open Terminal"))
        self.actionOpen_in_Terminal.setToolTip(
            _translate("MainWindow", "Open Terminal")
        )
        self.actionOpen_in_Terminal.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionRename_Entity.setText(_translate("MainWindow", "Rename Species..."))
        self.actionChange_Plugin.setText(_translate("MainWindow", "Change Plugin"))
        self.actionOpen_Plugins_Folder.setText(
            _translate("MainWindow", "Open Plugins Folder")
        )
