# Form implementation generated from reading ui file 'ui/projectselector.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProjectSelector(object):
    def setupUi(self, ProjectSelector):
        ProjectSelector.setObjectName("ProjectSelector")
        ProjectSelector.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        ProjectSelector.setEnabled(True)
        ProjectSelector.resize(900, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProjectSelector.sizePolicy().hasHeightForWidth())
        ProjectSelector.setSizePolicy(sizePolicy)
        ProjectSelector.setMinimumSize(QtCore.QSize(900, 480))
        ProjectSelector.setMaximumSize(QtCore.QSize(900, 480))
        ProjectSelector.setAcceptDrops(False)
        ProjectSelector.setWindowTitle("PorySuite-Z")
        ProjectSelector.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(parent=ProjectSelector)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(40, -1, 40, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_icon = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_icon.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_icon.setText("")
        self.label_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_icon.setObjectName("label_icon")
        self.verticalLayout.addWidget(self.label_icon)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.button_newproject = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_newproject.setMaximumSize(QtCore.QSize(250, 16777215))
        self.button_newproject.setObjectName("button_newproject")
        self.verticalLayout.addWidget(self.button_newproject)
        self.button_openproject = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_openproject.setMaximumSize(QtCore.QSize(250, 16777215))
        self.button_openproject.setObjectName("button_openproject")
        self.verticalLayout.addWidget(self.button_openproject)
        self.button_plugins = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_plugins.setMaximumSize(QtCore.QSize(250, 16777215))
        self.button_plugins.setObjectName("button_plugins")
        self.verticalLayout.addWidget(self.button_plugins)
        self.button_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_settings.setMaximumSize(QtCore.QSize(250, 16777215))
        self.button_settings.setObjectName("button_settings")
        self.verticalLayout.addWidget(self.button_settings)
        self.button_clear_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_clear_settings.setMaximumSize(QtCore.QSize(250, 16777215))
        self.button_clear_settings.setObjectName("button_clear_settings")
        self.verticalLayout.addWidget(self.button_clear_settings)
        self.button_quit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_quit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.button_quit.setFlat(False)
        self.button_quit.setObjectName("button_quit")
        self.verticalLayout.addWidget(self.button_quit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayout_projects = QtWidgets.QVBoxLayout()
        self.verticalLayout_projects.setObjectName("verticalLayout_projects")
        self.verticalLayout_2.addLayout(self.verticalLayout_projects)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        ProjectSelector.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProjectSelector)
        self.button_quit.clicked.connect(ProjectSelector.quit) # type: ignore
        self.button_newproject.clicked.connect(ProjectSelector.new_project) # type: ignore
        self.button_openproject.clicked.connect(ProjectSelector.open_existing_project) # type: ignore
        self.button_plugins.clicked.connect(ProjectSelector.open_plugins_folder) # type: ignore
        self.button_settings.clicked.connect(ProjectSelector.open_settings) # type: ignore
        self.button_clear_settings.clicked.connect(ProjectSelector.clear_settings) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProjectSelector)

    def retranslateUi(self, ProjectSelector):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("ProjectSelector", "PorySuite-Z"))
        self.label_3.setText(_translate("ProjectSelector", ""))
        self.button_newproject.setText(_translate("ProjectSelector", "New Project"))
        self.button_newproject.setToolTip(_translate("ProjectSelector",
            "Clone a fresh copy of pokefirered from GitHub, install the build tools, "
            "and compile it into a working ROM — all in one step.\n"
            "Requires Git. Choose a folder where the project will be created."))
        self.button_openproject.setText(_translate("ProjectSelector", "Open Project..."))
        self.button_openproject.setToolTip(_translate("ProjectSelector",
            "Open an existing project folder that has already been set up.\n"
            "The folder must contain a project.json file."))
        self.button_plugins.setText(_translate("ProjectSelector", "Open Plugins Folder"))
        self.button_settings.setText(_translate("ProjectSelector", "Settings..."))
        self.button_clear_settings.setText(_translate("ProjectSelector", "Clear Settings..."))
        self.button_quit.setText(_translate("ProjectSelector", "Quit"))
        self.label_4.setText(_translate("ProjectSelector", "Projects"))
