# Form implementation generated from reading ui file 'ui/plugininfo.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PluginInfoDialog(object):
    def setupUi(self, PluginInfoDialog):
        PluginInfoDialog.setObjectName("PluginInfoDialog")
        PluginInfoDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        PluginInfoDialog.resize(516, 565)
        PluginInfoDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PluginInfoDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.readme = QtWidgets.QTextBrowser(parent=PluginInfoDialog)
        self.readme.setOpenExternalLinks(True)
        self.readme.setObjectName("readme")
        self.verticalLayout.addWidget(self.readme)

        self.retranslateUi(PluginInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(PluginInfoDialog)

    def retranslateUi(self, PluginInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        PluginInfoDialog.setWindowTitle(_translate("PluginInfoDialog", "Dialog"))
